import type { EcosystemEntity } from '../types'
import { BASELINE_PILLAR_ID, BASELINE_DOMAIN_ID } from '../taxonomy'

/**
 * The universal baseline: what every domain above assumes.
 *
 * Listed once rather than repeated under thirty-one headings, and grouped
 * separately in the interface so it does not dilute the domain pages.
 */
export const baselineEntities: readonly EcosystemEntity[] = [
  {
    id: 'base-c-cpp',
    slug: 'c-and-cpp',
    name: 'C and C++',
    aliases: ['C', 'C++', 'C++11', 'C++14', 'C++17', 'C++20', 'C++23', 'embedded C', 'C/C++'],
    kind: 'language',
    vendorOrOwner: 'ISO/IEC JTC 1/SC 22',
    pillarIds: [BASELINE_PILLAR_ID],
    domainIds: [BASELINE_DOMAIN_ID],
    categoryIds: ['language'],
    summary:
      'The languages most real-time and embedded software is written in, and the implementation language of most robotics middleware. C where the memory model must be obvious, C++ where abstraction can be had without runtime cost.',
    useCases: ['Firmware and device drivers', 'Real-time control nodes where garbage collection is unacceptable'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['c', 'c++', 'embedded', 'real-time', 'systems programming', 'iso'],
  },
  {
    id: 'base-python',
    slug: 'python',
    name: 'Python',
    aliases: ['Python', 'NumPy', 'SciPy', 'pandas', 'Jupyter'],
    kind: 'language',
    vendorOrOwner: 'Python Software Foundation',
    pillarIds: [BASELINE_PILLAR_ID],
    domainIds: [BASELINE_DOMAIN_ID],
    categoryIds: ['language'],
    summary:
      'The default language for machine learning, data work, scripting and tooling, and one of the two first-class languages in ROS 2.',
    useCases: ['Model training and data analysis', 'Test automation and integration scripting', 'ROS 2 nodes where latency allows'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['python', 'numpy', 'scipy', 'pandas', 'scripting', 'ml', 'jupyter'],
  },
  {
    id: 'base-rust',
    slug: 'rust',
    name: 'Rust',
    aliases: ['Rust', 'cargo'],
    kind: 'language',
    vendorOrOwner: 'Rust Foundation',
    pillarIds: [BASELINE_PILLAR_ID],
    domainIds: [BASELINE_DOMAIN_ID],
    categoryIds: ['language'],
    summary:
      'A systems language with compile-time memory and concurrency guarantees, appearing in safety-critical and embedded work where whole classes of defect are worth designing out.',
    useCases: ['Embedded firmware without a garbage collector', 'Components where memory-safety defects are unacceptable'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['rust', 'memory safety', 'ownership', 'cargo', 'embedded', 'concurrency'],
  },
  {
    id: 'base-other-languages',
    slug: 'other-general-purpose-languages',
    name: 'Other general-purpose languages',
    aliases: ['Julia', 'Java', 'C#', 'Go', 'Kotlin', 'JavaScript', 'TypeScript', 'Node.js', 'R', 'Lua', 'SQL', 'Bash', 'Shell'],
    kind: 'language',
    pillarIds: [BASELINE_PILLAR_ID],
    domainIds: [BASELINE_DOMAIN_ID],
    categoryIds: ['language'],
    summary:
      'The wider language set an engineering system touches: SQL and shell almost everywhere, JavaScript and TypeScript for interfaces and Node-RED flows, C# and Java in enterprise and HMI layers, Julia and R in numerical and statistical work, and Lua as an embedded scripting layer.',
    useCases: ['Querying a historian or MES database', 'Web-based operator interfaces and dashboards', 'Statistical analysis of test data'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['sql', 'javascript', 'typescript', 'java', 'c#', 'go', 'julia', 'r', 'lua', 'bash'],
  },
  {
    id: 'base-hdl',
    slug: 'hardware-description-languages',
    name: 'Hardware description languages',
    aliases: ['Verilog', 'SystemVerilog', 'VHDL', 'HDL'],
    kind: 'language',
    vendorOrOwner: 'IEEE',
    pillarIds: [BASELINE_PILLAR_ID],
    domainIds: [BASELINE_DOMAIN_ID],
    categoryIds: ['language'],
    summary:
      'Languages that describe hardware structure and timing rather than sequential execution, with SystemVerilog adding the constructs used for constrained-random verification.',
    useCases: ['Describing synthesisable logic for an FPGA or ASIC', 'Writing a verification testbench'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['verilog', 'systemverilog', 'vhdl', 'rtl', 'synthesis', 'testbench', 'ieee'],
  },
  {
    id: 'base-assembly',
    slug: 'assembly-languages',
    name: 'Assembly languages',
    aliases: ['Assembly', 'ARM assembly', 'RISC-V assembly', 'x86 assembly', 'GNU assembler', 'GAS'],
    kind: 'language',
    pillarIds: [BASELINE_PILLAR_ID],
    domainIds: [BASELINE_DOMAIN_ID],
    categoryIds: ['language'],
    summary:
      'Architecture-specific instruction sets, written directly in startup code, interrupt prologues and hand-optimised inner loops. Arm, RISC-V and x86 are the architectures; GNU is a toolchain and assembler syntax rather than an architecture.',
    useCases: ['Processor startup and vector table code', 'Reading compiler output when timing is critical'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['assembly', 'arm', 'risc-v', 'x86', 'gnu', 'startup', 'instruction set'],
  },
  {
    id: 'base-linux',
    slug: 'linux',
    name: 'Linux',
    aliases: ['Linux', 'Ubuntu', 'Debian', 'GNU/Linux'],
    kind: 'os',
    vendorOrOwner: 'Linux kernel community',
    pillarIds: [BASELINE_PILLAR_ID],
    domainIds: [BASELINE_DOMAIN_ID],
    categoryIds: ['os-rtos'],
    summary:
      'The operating system most robotics, edge and server software targets, with Ubuntu the reference distribution for ROS 2 and Debian common on embedded boards.',
    useCases: ['Robot companion computers and edge gateways', 'Build and CI infrastructure'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['linux', 'ubuntu', 'debian', 'kernel', 'systemd', 'ros'],
  },
  {
    id: 'base-windows',
    slug: 'windows',
    name: 'Windows and Windows IoT',
    aliases: ['Windows', 'Windows IoT'],
    kind: 'os',
    vendorOrOwner: 'Microsoft',
    pillarIds: [BASELINE_PILLAR_ID],
    domainIds: [BASELINE_DOMAIN_ID],
    categoryIds: ['os-rtos'],
    summary:
      'The platform most industrial engineering software runs on, including the PLC and SCADA environments, and the operating system on many HMI and panel PCs.',
    useCases: ['Running vendor engineering tooling', 'SCADA servers and operator stations'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['windows', 'windows iot', 'scada', 'engineering workstation', 'panel pc'],
  },
  {
    id: 'base-vcs',
    slug: 'version-control-and-collaboration',
    name: 'Version control and collaboration',
    aliases: ['Git', 'GitHub', 'GitLab', 'Bitbucket', 'Azure DevOps', 'SVN', 'Subversion', 'Perforce', 'Mercurial'],
    kind: 'software',
    vendorOrOwner: 'Git project, GitHub, GitLab, Atlassian, Microsoft',
    pillarIds: [BASELINE_PILLAR_ID],
    domainIds: [BASELINE_DOMAIN_ID],
    categoryIds: ['ide-toolchain'],
    summary:
      'Distributed version control and the hosting platforms built on it, including the review and issue workflow that is how most engineering change is actually proposed and recorded.',
    useCases: ['Traceable change history for an audited codebase', 'Review before merge as a quality gate'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['git', 'github', 'gitlab', 'branch', 'merge request', 'review', 'perforce'],
  },
  {
    id: 'base-build',
    slug: 'build-and-package-systems',
    name: 'Build and package systems',
    aliases: ['CMake', 'Make', 'Ninja', 'Meson', 'Bazel', 'colcon', 'catkin', 'Gradle', 'Maven', 'apt', 'pip', 'conda', 'mamba', 'vcpkg', 'Conan', 'npm', 'cargo', 'rosdep', 'brew'],
    kind: 'software',
    vendorOrOwner: 'Kitware, open-source projects',
    pillarIds: [BASELINE_PILLAR_ID],
    domainIds: [BASELINE_DOMAIN_ID],
    categoryIds: ['ide-toolchain'],
    summary:
      'Build orchestration and dependency management, including the ROS-specific colcon workspace tooling and the C++ package managers that make a reproducible dependency set possible.',
    useCases: ['Reproducible cross-compilation for an embedded target', 'Managing a multi-package ROS 2 workspace'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['cmake', 'ninja', 'bazel', 'colcon', 'conan', 'vcpkg', 'pip', 'conda', 'cross-compile'],
  },
  {
    id: 'base-cicd',
    slug: 'ci-cd-systems',
    name: 'CI/CD systems',
    aliases: ['Jenkins', 'GitLab CI', 'GitHub Actions', 'CircleCI', 'ArgoCD', 'Tekton', 'continuous integration'],
    kind: 'software',
    vendorOrOwner: 'Jenkins project, GitLab, GitHub, CircleCI',
    pillarIds: [BASELINE_PILLAR_ID],
    domainIds: [BASELINE_DOMAIN_ID],
    categoryIds: ['ide-toolchain'],
    summary:
      'Automated build, test and deployment pipelines, which in embedded and robotics work increasingly include hardware-in-the-loop stages rather than unit tests alone.',
    useCases: ['Running the full test suite on every change', 'Producing signed, versioned firmware artefacts automatically'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['jenkins', 'github actions', 'gitlab ci', 'pipeline', 'artefact', 'automation', 'hil'],
  },
  {
    id: 'base-editors',
    slug: 'editors-and-ides',
    name: 'Editors and IDEs',
    aliases: ['VS Code', 'Visual Studio Code', 'CLion', 'PyCharm', 'IntelliJ', 'Visual Studio', 'Eclipse', 'Vim', 'Neovim', 'Emacs'],
    kind: 'software',
    vendorOrOwner: 'Microsoft, JetBrains, Eclipse Foundation and open-source projects',
    pillarIds: [BASELINE_PILLAR_ID],
    domainIds: [BASELINE_DOMAIN_ID],
    categoryIds: ['ide-toolchain'],
    summary:
      'General-purpose development environments, with VS Code the common denominator across embedded, robotics and web work through its extension ecosystem.',
    useCases: ['One environment across several languages and targets', 'Remote development onto a robot or edge device'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['vs code', 'clion', 'pycharm', 'eclipse', 'vim', 'emacs', 'lsp', 'remote development'],
  },
  {
    id: 'base-docs',
    slug: 'documentation-tooling',
    name: 'Documentation tooling',
    aliases: ['Sphinx', 'Doxygen', 'MkDocs', 'Docusaurus', 'Markdown'],
    kind: 'software',
    vendorOrOwner: 'Open-source projects',
    pillarIds: [BASELINE_PILLAR_ID],
    domainIds: [BASELINE_DOMAIN_ID],
    categoryIds: ['ide-toolchain'],
    summary:
      'Documentation generators that build reference material from source comments and Markdown, keeping documentation in the repository and therefore in the same review process as the code.',
    useCases: ['API reference generated from annotated headers', 'Versioned project documentation published from source'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['sphinx', 'doxygen', 'mkdocs', 'docusaurus', 'markdown', 'api reference'],
  },
  {
    id: 'base-networking',
    slug: 'networking-fundamentals',
    name: 'Networking fundamentals',
    aliases: ['TCP/IP', 'UDP', 'HTTP', 'REST', 'gRPC', 'WebSocket', 'SSH', 'TLS', 'mTLS', 'DNS', 'NTP', 'PTP', 'IEEE 1588'],
    kind: 'protocol',
    vendorOrOwner: 'IETF and IEEE',
    pillarIds: [BASELINE_PILLAR_ID],
    domainIds: [BASELINE_DOMAIN_ID],
    categoryIds: ['protocol'],
    summary:
      'The general-purpose network stack underneath everything else, including the precision time protocol that industrial synchronisation and sequence-of-events recording depend on.',
    useCases: ['Sub-microsecond clock alignment across nodes', 'Mutually authenticated device-to-server links'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['tcp/ip', 'udp', 'grpc', 'tls', 'mtls', 'ptp', 'ntp', 'ieee 1588', 'dns'],
  },
  {
    id: 'base-data-formats',
    slug: 'data-formats',
    name: 'Data formats',
    aliases: ['JSON', 'XML', 'YAML', 'TOML', 'Protobuf', 'Protocol Buffers', 'FlatBuffers', 'CBOR', 'Parquet', 'HDF5', 'CSV', 'ROS bag', 'rosbag', 'MCAP', 'ulog'],
    kind: 'protocol',
    vendorOrOwner: 'Google, Apache Software Foundation, HDF Group, Foxglove and others',
    pillarIds: [BASELINE_PILLAR_ID],
    domainIds: [BASELINE_DOMAIN_ID],
    categoryIds: ['protocol'],
    summary:
      'Configuration, interchange and recording formats, including the columnar and scientific formats used for large measurement datasets and the MCAP container that has become the standard robotics log format.',
    useCases: [
      'Efficient schema-checked messages on a constrained link',
      'Recording synchronised multi-topic sensor data for replay',
      'Storing large time-series measurement campaigns',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['json', 'yaml', 'protobuf', 'flatbuffers', 'parquet', 'hdf5', 'mcap', 'rosbag', 'ulog'],
  },
  {
    id: 'base-numeric-libraries',
    slug: 'numerical-libraries',
    name: 'Numerical libraries',
    aliases: ['NumPy', 'SciPy', 'Eigen', 'BLAS', 'LAPACK', 'OpenBLAS', 'Intel MKL', 'Armadillo', 'Boost'],
    kind: 'library',
    vendorOrOwner: 'NumFOCUS, Eigen project, Intel and open-source projects',
    pillarIds: [BASELINE_PILLAR_ID],
    domainIds: [BASELINE_DOMAIN_ID],
    categoryIds: ['framework'],
    summary:
      'Linear algebra and scientific computing underneath almost every other library here, with Eigen the usual choice in C++ robotics code and BLAS and LAPACK implementations behind the numerical Python stack.',
    useCases: ['Matrix operations inside a control or estimation loop', 'Numerical prototyping before porting to C++'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['numpy', 'scipy', 'eigen', 'blas', 'lapack', 'mkl', 'boost', 'linear algebra'],
  },
] as const
