import type { EcosystemEntity } from '../types'

/**
 * Single-board computers, maker boards, edge compute and the silicon
 * families behind them.
 *
 * Every entry here is an ecosystem reference: a fact about the field, not a
 * claim about Saj. Where a board family has many generations, the
 * generations live in `models` rather than as separate top-level entries,
 * so the scope keeps every specific board it names without turning the page
 * into hundreds of near-identical cards.
 *
 * Three corrections are applied here and stated on the records themselves:
 * Particle is the brand ("Particle IO" is a search alias only); Jetson Mate
 * is a third-party carrier and is not presented as an NVIDIA-built Jetson;
 * and Arduino EduPack is an education bundle rather than a board family.
 */

export const computeBoardEntities: readonly EcosystemEntity[] = [
  {
    id: 'ent-raspberry-pi',
    slug: 'raspberry-pi',
    name: 'Raspberry Pi single-board computers',
    aliases: ['Raspberry Pi', 'RPi', 'Pi', 'Raspberry Pi 5', 'Raspberry Pi 4', 'Pi Zero'],
    kind: 'hardware-family',
    vendorOrOwner: 'Raspberry Pi Ltd',
    pillarIds: ['compute', 'ai', 'networks'],
    domainIds: ['firmware', 'architecture', 'edge-ai', 'iiot'],
    categoryIds: ['hardware-family', 'accelerator'],
    summary:
      'Arm Linux single-board computers spanning the credit-card Model B line, the compact Zero line and the keyboard-form Pi 500 series, widely used as edge compute, HMI and gateway hardware.',
    useCases: [
      'Edge gateway between field devices and a cloud or on-premises broker',
      'ROS 2 companion computer on a small mobile robot',
      'Panel or kiosk HMI where an industrial panel PC is not warranted',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: ['src-rpi-products'],
    coverageKind: 'ecosystem-reference',
    models: [
      {
        name: 'Raspberry Pi 5',
        lifecycle: 'current',
        lifecycleAsOf: '2026-07-30',
        note: 'BCM2712 with the RP1 I/O controller, PCIe connector and on-board RTC. A 1GB variant joined the line in April 2026.',
      },
      { name: 'Raspberry Pi 500', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'Pi 5 class hardware in a keyboard.' },
      { name: 'Raspberry Pi 500+', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'The most recent addition to the keyboard-form line.' },
      { name: 'Raspberry Pi 4 Model B', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30' },
      { name: 'Raspberry Pi Zero 2 W', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30' },
      { name: 'Raspberry Pi Zero W', aliases: ['Pi Zero W'], lifecycle: 'legacy', lifecycleAsOf: '2026-07-30' },
      { name: 'Raspberry Pi Zero', lifecycle: 'legacy', lifecycleAsOf: '2026-07-30' },
      { name: 'Raspberry Pi 3 Model B+', lifecycle: 'legacy', lifecycleAsOf: '2026-07-30' },
      { name: 'Raspberry Pi 3', lifecycle: 'legacy', lifecycleAsOf: '2026-07-30' },
      { name: 'Raspberry Pi 2', lifecycle: 'legacy', lifecycleAsOf: '2026-07-30' },
      { name: 'Raspberry Pi 1', lifecycle: 'legacy', lifecycleAsOf: '2026-07-30' },
    ],
    keywords: ['sbc', 'linux', 'arm', 'edge', 'gateway', 'bcm2712', 'raspberry pi'],
  },
  {
    id: 'ent-rpi-compute-module',
    slug: 'raspberry-pi-compute-module',
    name: 'Raspberry Pi Compute Module',
    aliases: ['Compute Module', 'CM4', 'CM5', 'Compute Module 4', 'Compute Module 5', 'Compute Module Zero'],
    kind: 'hardware-family',
    vendorOrOwner: 'Raspberry Pi Ltd',
    familyId: 'ent-raspberry-pi',
    pillarIds: ['compute', 'ot', 'networks'],
    domainIds: ['firmware', 'architecture', 'iiot'],
    categoryIds: ['hardware-family', 'hardware-model'],
    summary:
      'The system-on-module form of the Raspberry Pi, intended to be designed onto a custom carrier board for embedded and industrial products rather than used as a bare board.',
    useCases: [
      'Embedding Pi-class Linux compute into a custom product carrier',
      'Industrial gateway designs needing a defined supply lifetime',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: ['src-rpi-cm'],
    coverageKind: 'ecosystem-reference',
    models: [
      {
        name: 'Compute Module 5',
        aliases: ['CM5'],
        lifecycle: 'current',
        lifecycleAsOf: '2026-07-30',
        note: 'Pi 5 class. Has no user-exposed PCIe lane on the module itself, so a Pi 5-format carrier is required to use PCIe accessories such as the AI HAT+ 2.',
      },
      { name: 'Compute Module Zero', lifecycle: 'unknown', lifecycleAsOf: '2026-07-30', note: 'Named in the supplied scope. Status not confirmed against a primary Raspberry Pi source at the review date.' },
      { name: 'Compute Module 4', aliases: ['CM4'], lifecycle: 'maintained', lifecycleAsOf: '2026-07-30' },
      { name: 'Compute Module 3+', aliases: ['CM3+'], lifecycle: 'legacy', lifecycleAsOf: '2026-07-30' },
      { name: 'Compute Module 3', aliases: ['CM3'], lifecycle: 'legacy', lifecycleAsOf: '2026-07-30' },
    ],
    keywords: ['som', 'system on module', 'carrier board', 'compute module', 'industrial'],
  },
  {
    id: 'ent-rpi-pico',
    slug: 'raspberry-pi-pico',
    name: 'Raspberry Pi Pico and RP-series microcontrollers',
    aliases: ['Pico', 'Pico 2', 'Pico 2 W', 'RP2040', 'RP2350', 'Raspberry Pi Pico'],
    kind: 'hardware-family',
    vendorOrOwner: 'Raspberry Pi Ltd',
    pillarIds: ['compute'],
    domainIds: ['firmware', 'realtime'],
    categoryIds: ['hardware-family', 'hardware-model'],
    summary:
      'Low-cost microcontroller boards built on the in-house RP2040 and RP2350 silicon, notable for programmable I/O state machines and, on RP2350, selectable Arm or RISC-V cores.',
    useCases: [
      'Deterministic I/O and protocol bit-banging via the PIO blocks',
      'Low-cost sensor node or motor interface board',
      'Teaching embedded C and MicroPython',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: ['src-rpi-pico'],
    coverageKind: 'ecosystem-reference',
    models: [
      { name: 'Pico 2', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'RP2350, 520KB SRAM and 4MB flash, with optional RISC-V cores.' },
      { name: 'Pico 2 W', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'Adds 2.4GHz 802.11n wireless LAN and Bluetooth 5.2.' },
      { name: 'Pico', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30', note: 'RP2040.' },
      { name: 'Pico W', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30' },
    ],
    keywords: ['microcontroller', 'mcu', 'rp2040', 'rp2350', 'pio', 'risc-v', 'micropython'],
  },
  {
    id: 'ent-rpi-camera',
    slug: 'raspberry-pi-cameras',
    name: 'Raspberry Pi camera modules',
    aliases: ['Pi Camera', 'Camera Module 3', 'HQ Camera', 'Global Shutter Camera', 'AI Camera', 'Pi Camera Module v2'],
    kind: 'hardware-family',
    vendorOrOwner: 'Raspberry Pi Ltd',
    familyId: 'ent-raspberry-pi',
    pillarIds: ['electronics', 'controls'],
    domainIds: ['optics', 'vision'],
    categoryIds: ['hardware-family', 'sensor'],
    summary:
      'CSI-2 attached camera modules for the Pi, ranging from fixed-focus consumer sensors to an interchangeable-lens HQ module, a global-shutter module for motion, and an AI Camera with on-sensor inference.',
    useCases: [
      'Machine-vision capture where a global shutter avoids rolling-shutter skew',
      'On-sensor inference that keeps the host CPU free',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: ['src-rpi-camera'],
    coverageKind: 'ecosystem-reference',
    models: [
      { name: 'Raspberry Pi AI Camera', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'Sony IMX500 sensor with inference on the sensor package.' },
      { name: 'Camera Module 3', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'Global Shutter Camera', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'HQ Camera', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'Camera Module v2', lifecycle: 'legacy', lifecycleAsOf: '2026-07-30' },
    ],
    keywords: ['camera', 'csi-2', 'imx500', 'global shutter', 'machine vision'],
  },
  {
    id: 'ent-rpi-ai-hat',
    slug: 'raspberry-pi-ai-accelerators',
    name: 'Raspberry Pi AI accelerators',
    aliases: ['AI HAT+', 'AI HAT+ 2', 'AI Kit', 'Raspberry Pi AI HAT'],
    kind: 'hardware-family',
    vendorOrOwner: 'Raspberry Pi Ltd',
    familyId: 'ent-raspberry-pi',
    pillarIds: ['ai', 'compute'],
    domainIds: ['edge-ai', 'architecture'],
    categoryIds: ['hardware-family', 'accelerator'],
    summary:
      'PCIe-attached neural accelerators for the Pi 5, built around Hailo silicon, which move inference off the CPU for camera and vision workloads.',
    useCases: [
      'Running detection or segmentation at frame rate on a Pi 5',
      'On-device generative and vision-language workloads at the edge',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: ['src-rpi-aihat', 'src-hailo'],
    coverageKind: 'ecosystem-reference',
    models: [
      {
        name: 'AI HAT+ 2',
        lifecycle: 'current',
        lifecycleAsOf: '2026-07-30',
        note: 'Single 40 TOPS variant built on the Hailo-10H, with 8GB of dedicated LPDDR4 alongside the accelerator.',
      },
      { name: 'AI HAT+', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'Available in 13 TOPS and 26 TOPS variants.' },
      { name: 'Raspberry Pi AI Kit', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30', note: 'Hailo-8L module paired with the M.2 HAT+.' },
    ],
    keywords: ['npu', 'accelerator', 'hailo', 'tops', 'inference', 'pcie'],
  },

  {
    id: 'ent-arduino',
    slug: 'arduino',
    name: 'Arduino boards',
    aliases: ['Arduino', 'Arduino UNO', 'Arduino Nano', 'Arduino Mega', 'Arduino Due', 'Arduino Leonardo', 'Arduino Micro'],
    kind: 'hardware-family',
    vendorOrOwner: 'Arduino (Qualcomm)',
    pillarIds: ['compute', 'electronics'],
    domainIds: ['firmware', 'instrumentation'],
    categoryIds: ['hardware-family', 'hardware-model'],
    summary:
      'The reference open-hardware microcontroller ecosystem, spanning the classic 8-bit UNO through 32-bit Renesas and Arm boards to Linux-capable designs, with a single toolchain across the range.',
    useCases: [
      'Rapid prototyping of a sensor or actuator interface',
      'Teaching embedded programming before moving to vendor toolchains',
      'Small production runs where the core is carried onto a custom board',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: ['src-arduino-hardware', 'src-arduino-unoq'],
    coverageKind: 'ecosystem-reference',
    models: [
      {
        name: 'UNO Q',
        lifecycle: 'current',
        lifecycleAsOf: '2026-07-30',
        note: 'Dual-brain design: a Qualcomm Dragonwing QRB2210 running Debian Linux alongside an STM32U585 for real-time work. Announced October 2025 with the Qualcomm acquisition; a 4GB RAM, 32GB eMMC variant followed in January 2026.',
      },
      { name: 'UNO R4 Minima', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'Renesas RA4M1.' },
      { name: 'UNO R4 WiFi', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'Nano R4', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'Renesas RA4M1 in the Nano form factor, positioned as the production step up from UNO R4 prototyping.' },
      { name: 'Nano Matter', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'Targets the Matter smart-home standard. Not confirmed against a primary Arduino source at the review date.' },
      { name: 'Nano ESP32', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'GIGA R1 WiFi', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'Portenta H7', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'Portenta C33', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'Portenta X8', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'Linux-capable industrial module.' },
      { name: 'UNO R3', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30', note: 'The long-running ATmega328P board.' },
      { name: 'Nano 33 IoT', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30' },
      { name: 'Nano 33 BLE Sense Rev2', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30' },
      { name: 'Nano RP2040 Connect', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30' },
      { name: 'Mega 2560', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30' },
      { name: 'Due', lifecycle: 'legacy', lifecycleAsOf: '2026-07-30' },
      { name: 'Leonardo', lifecycle: 'legacy', lifecycleAsOf: '2026-07-30' },
      { name: 'Micro', lifecycle: 'legacy', lifecycleAsOf: '2026-07-30' },
    ],
    keywords: ['arduino', 'mcu', 'prototyping', 'atmega', 'renesas ra4m1', 'qualcomm dragonwing', 'open hardware'],
  },
  {
    id: 'ent-arduino-mkr',
    slug: 'arduino-mkr',
    name: 'Arduino MKR family',
    aliases: ['MKR', 'MKR WiFi 1010', 'MKR WAN 1310', 'MKR GSM 1400', 'MKR NB 1500', 'MKR Vidor 4000', 'MKR Zero', 'MKR Fox', 'MKR GPRS'],
    kind: 'hardware-family',
    vendorOrOwner: 'Arduino (Qualcomm)',
    familyId: 'ent-arduino',
    pillarIds: ['compute', 'networks'],
    domainIds: ['firmware', 'iiot'],
    categoryIds: ['hardware-family', 'hardware-model'],
    summary:
      'A common SAMD-based form factor with interchangeable radios, so the same footprint covers Wi-Fi, LoRa, cellular and narrowband connectivity.',
    useCases: [
      'Connected sensor node where the radio choice may change late',
      'Battery-powered LoRaWAN or NB-IoT field device',
    ],
    lifecycle: 'maintained',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: ['src-arduino-hardware'],
    coverageKind: 'ecosystem-reference',
    models: [
      { name: 'MKR WiFi 1010', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30' },
      { name: 'MKR WAN 1310', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30', note: 'LoRaWAN.' },
      { name: 'MKR NB 1500', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30', note: 'NB-IoT.' },
      { name: 'MKR GSM 1400', lifecycle: 'legacy', lifecycleAsOf: '2026-07-30' },
      { name: 'MKR Vidor 4000', lifecycle: 'legacy', lifecycleAsOf: '2026-07-30', note: 'Carries an Intel Cyclone 10 FPGA alongside the SAMD21.' },
      { name: 'MKR Zero', lifecycle: 'legacy', lifecycleAsOf: '2026-07-30' },
      { name: 'MKR FOX 1200', lifecycle: 'discontinued', lifecycleAsOf: '2026-07-30', note: 'Sigfox.' },
      { name: 'MKR GPRS 1400', lifecycle: 'discontinued', lifecycleAsOf: '2026-07-30' },
    ],
    keywords: ['mkr', 'samd21', 'lorawan', 'nb-iot', 'sigfox', 'connectivity'],
  },
  {
    id: 'ent-arduino-nicla',
    slug: 'arduino-nicla',
    name: 'Arduino Nicla family',
    aliases: ['Nicla', 'Nicla Sense ME', 'Nicla Vision', 'Nicla Voice'],
    kind: 'hardware-family',
    vendorOrOwner: 'Arduino (Qualcomm)',
    familyId: 'ent-arduino',
    pillarIds: ['ai', 'electronics'],
    domainIds: ['edge-ai', 'instrumentation'],
    categoryIds: ['hardware-family', 'sensor'],
    summary:
      'Very small sensor-and-inference boards aimed at TinyML: an environmental and motion sensing variant, a camera variant and an always-on audio variant.',
    useCases: ['Battery-powered condition monitoring with on-board inference', 'Keyword spotting without a network round trip'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: ['src-arduino-hardware'],
    coverageKind: 'ecosystem-reference',
    models: [
      { name: 'Nicla Sense ME', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'Nicla Vision', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'Nicla Voice', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
    ],
    keywords: ['tinyml', 'nicla', 'sensor fusion', 'edge inference'],
  },
  {
    id: 'ent-arduino-opta',
    slug: 'arduino-opta',
    name: 'Arduino Opta',
    aliases: ['Opta', 'Arduino Opta micro-PLC'],
    kind: 'hardware-family',
    vendorOrOwner: 'Arduino (Qualcomm)',
    familyId: 'ent-arduino',
    pillarIds: ['ot', 'compute', 'networks'],
    domainIds: ['industrial-automation', 'iiot'],
    categoryIds: ['hardware-family', 'vendor-platform'],
    summary:
      'A DIN-rail micro-PLC developed with Finder that accepts both IEC 61131-3 programming and the Arduino sketch model, bridging maker tooling and industrial control.',
    useCases: ['Small machine control on a DIN rail', 'Retrofitting IIoT telemetry onto existing plant'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: ['src-arduino-hardware'],
    coverageKind: 'ecosystem-reference',
    keywords: ['plc', 'din rail', 'iec 61131-3', 'micro plc', 'finder'],
  },
  {
    id: 'ent-arduino-education',
    slug: 'arduino-education',
    name: 'Arduino education products',
    aliases: ['EduPack', 'Arduino EduPack', 'Arduino Education Starter Kit', 'Arduino Student Kit'],
    kind: 'vendor-platform',
    vendorOrOwner: 'Arduino (Qualcomm)',
    familyId: 'ent-arduino',
    pillarIds: ['compute'],
    domainIds: ['firmware'],
    categoryIds: ['vendor-platform'],
    summary:
      'Classroom bundles pairing existing Arduino boards with curriculum, components and lesson material. A packaging and teaching product rather than a distinct board family.',
    useCases: ['Structured classroom delivery of embedded fundamentals'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: ['src-arduino-hardware'],
    coverageKind: 'ecosystem-reference',
    keywords: ['education', 'edupack', 'curriculum', 'teaching kit'],
  },

  {
    id: 'ent-particle',
    slug: 'particle',
    name: 'Particle connected device platform',
    aliases: ['Particle', 'Particle IO', 'Particle.io', 'Spark'],
    kind: 'hardware-family',
    vendorOrOwner: 'Particle Industries',
    pillarIds: ['networks', 'compute'],
    domainIds: ['iiot', 'firmware'],
    categoryIds: ['hardware-family', 'vendor-platform'],
    summary:
      'An IoT platform pairing Wi-Fi, cellular and tracking hardware with Device OS and a managed cloud, so fleet connectivity, OTA update and device identity arrive as one product rather than as separate integrations.',
    useCases: [
      'Cellular-connected asset telemetry with managed OTA across a fleet',
      'Moving a prototype onto a production system-on-module without rewriting firmware',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: ['src-particle-docs', 'src-particle-changelog'],
    coverageKind: 'ecosystem-reference',
    models: [
      { name: 'Tachyon', lifecycle: 'preview', lifecycleAsOf: '2026-07-30', note: 'Alpha programme, with devices distributed in North America, Canada and the UK at the review date.' },
      { name: 'Muon', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'Raspberry Pi form factor combining cellular, Wi-Fi, BLE, GNSS, LoRaWAN and Ethernet.' },
      { name: 'M-SoM', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'The production module that Muon firmware ports onto.' },
      { name: 'Photon 2', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'Wi-Fi. The recommended migration from Argon.' },
      { name: 'P2', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'The module form of Photon 2.' },
      { name: 'Boron', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'Flagship cellular development board.' },
      { name: 'B-SoM', aliases: ['B-Series'], lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'Tracker One', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'Enclosed asset tracker.' },
      { name: 'Tracker SoM', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'Monitor One', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'Named in the supplied scope. Not confirmed against a primary Particle source at the review date.' },
      { name: 'Argon', lifecycle: 'legacy', lifecycleAsOf: '2026-07-30', note: 'Gen 3 Wi-Fi board. Particle publishes a Photon 2 migration guide for Argon designs.' },
      { name: 'E-Series', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30' },
      { name: 'Electron', lifecycle: 'legacy', lifecycleAsOf: '2026-07-30', note: 'Earlier cellular generation.' },
      { name: 'Photon', lifecycle: 'discontinued', lifecycleAsOf: '2026-07-30', note: 'Discontinued. Particle recommends Argon or Photon 2 as substitutes.' },
      { name: 'P1', lifecycle: 'legacy', lifecycleAsOf: '2026-07-30' },
      {
        name: 'Xenon',
        lifecycle: 'discontinued',
        lifecycleAsOf: '2026-07-30',
        note: 'Discontinued with Particle Mesh. No longer manufactured, unsupported by the mobile apps, and limited to Device OS 1.5.2 or earlier.',
      },
    ],
    keywords: ['iot', 'cellular', 'device os', 'ota', 'fleet', 'particle io', 'lorawan', 'tracker'],
  },

  {
    id: 'ent-nvidia-jetson',
    slug: 'nvidia-jetson',
    name: 'NVIDIA Jetson',
    aliases: ['Jetson', 'NVIDIA Jetson', 'Jetson Orin', 'Jetson Thor', 'Jetson Nano', 'Jetson Xavier', 'AGX Orin'],
    kind: 'hardware-family',
    vendorOrOwner: 'NVIDIA',
    pillarIds: ['ai', 'compute', 'controls'],
    domainIds: ['edge-ai', 'architecture', 'vision', 'navigation'],
    categoryIds: ['hardware-family', 'accelerator'],
    summary:
      'GPU-accelerated Arm modules for robotics and edge AI, sold as production modules with matching developer kits, and programmed through the CUDA and TensorRT stack via JetPack.',
    useCases: [
      'Running perception and planning on a mobile robot without a tethered workstation',
      'Multi-camera inference at the edge in an inspection cell',
      'Consolidating several inference workloads onto one power-budgeted module',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: ['src-nvidia-jetson-modules', 'src-nvidia-jetson-thor', 'src-nvidia-t4000'],
    coverageKind: 'ecosystem-reference',
    models: [
      {
        name: 'Jetson AGX Thor',
        lifecycle: 'current',
        lifecycleAsOf: '2026-07-30',
        note: 'Blackwell-generation flagship, up to 2070 FP4 TFLOPS and 128GB, configurable 40W to 130W.',
      },
      { name: 'Jetson T5000', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'Thor module: 2560 CUDA cores, 14 Arm cores, 128GB LPDDR5X, roughly 130W.' },
      { name: 'Jetson T4000', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'Thor module: up to 1200 FP4 TFLOPS, 64GB, configurable 40W to 70W.' },
      { name: 'Jetson T3000', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'Mainstream Thor module announced July 2026: up to 865 FP4 TFLOPS, 1536-core Blackwell GPU, 32GB LPDDR5X.' },
      { name: 'Jetson T2000', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'Mainstream Thor module announced July 2026: up to 400 TFLOPS, 1024-core Blackwell GPU, 16GB LPDDR5.' },
      { name: 'Jetson Orin Nano', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'Jetson Orin NX', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'Jetson AGX Orin', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: '32GB and 64GB variants.' },
      { name: 'Jetson Xavier NX', lifecycle: 'legacy', lifecycleAsOf: '2026-07-30' },
      { name: 'Jetson AGX Xavier', lifecycle: 'legacy', lifecycleAsOf: '2026-07-30' },
      { name: 'Jetson Nano', lifecycle: 'legacy', lifecycleAsOf: '2026-07-30', note: 'The original entry module, superseded by Orin Nano.' },
    ],
    keywords: ['jetson', 'cuda', 'tensorrt', 'jetpack', 'edge ai', 'blackwell', 'orin', 'thor', 'gpu'],
  },
  {
    id: 'ent-jetson-carriers',
    slug: 'jetson-carrier-boards',
    name: 'Jetson carrier boards and third-party carriers',
    aliases: ['Jetson Carrier boards', 'Jetson Mate', 'Jetson developer kit carrier'],
    kind: 'hardware-family',
    vendorOrOwner: 'Various third parties',
    pillarIds: ['compute'],
    domainIds: ['architecture', 'firmware'],
    categoryIds: ['hardware-family', 'legacy-reference'],
    summary:
      'Baseboards that break a Jetson module out to connectors. NVIDIA ships reference carriers inside its developer kits; the wider carrier market, including cluster boards such as Seeed Studio Jetson Mate, is third-party and not NVIDIA-manufactured.',
    useCases: [
      'Taking a Jetson module into a custom enclosure with the required I/O',
      'Bench clustering of several modules for build or test',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: ['src-nvidia-jetson-modules'],
    coverageKind: 'ecosystem-reference',
    models: [
      { name: 'NVIDIA Jetson developer kit reference carriers', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'Developer kits pair a module with an NVIDIA reference carrier; production designs use a custom or third-party carrier.' },
      { name: 'Jetson Mate', lifecycle: 'unknown', lifecycleAsOf: '2026-07-30', note: 'A Seeed Studio cluster carrier, not an NVIDIA-manufactured Jetson product. Listed here to correct that association.' },
    ],
    keywords: ['carrier board', 'baseboard', 'developer kit', 'jetson mate', 'seeed'],
  },
  {
    id: 'ent-nvidia-clara-agx',
    slug: 'nvidia-clara-agx',
    name: 'NVIDIA Clara AGX',
    aliases: ['Clara AGX', 'NVIDIA Clara AGX developer kit'],
    kind: 'hardware-family',
    vendorOrOwner: 'NVIDIA',
    pillarIds: ['ai', 'physical'],
    domainIds: ['edge-ai', 'biomechanical'],
    categoryIds: ['hardware-family', 'legacy-reference'],
    summary:
      'A medical-imaging and healthcare-instrument edge platform. Superseded within NVIDIA by the Holoscan line for sensor-processing applications.',
    useCases: ['Real-time medical instrument sensor processing'],
    lifecycle: 'legacy',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: ['src-nvidia-jetson-modules'],
    coverageKind: 'ecosystem-reference',
    keywords: ['clara', 'medical imaging', 'holoscan', 'healthcare edge'],
  },

  {
    id: 'ent-esp32',
    slug: 'espressif-esp32',
    name: 'Espressif ESP32',
    aliases: ['ESP32', 'ESP32-S3', 'ESP32-C3', 'ESP32-C6', 'ESP32-S2', 'ESP32-H2', 'ESP32-P4'],
    kind: 'hardware-family',
    vendorOrOwner: 'Espressif Systems',
    pillarIds: ['compute', 'networks', 'ai'],
    domainIds: ['firmware', 'iiot', 'edge-ai'],
    categoryIds: ['hardware-family', 'electronic-component'],
    summary:
      'Wi-Fi and Bluetooth microcontrollers spanning Xtensa and RISC-V cores, widely used where a radio, a reasonable core and a low bill of materials all matter at once.',
    useCases: [
      'Wi-Fi or BLE connected sensor and control node',
      'Low-cost edge inference on the S3 vector extensions',
      'Thread and Zigbee border devices on the C6 and H2',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: ['src-espressif'],
    coverageKind: 'ecosystem-reference',
    models: [
      { name: 'ESP32-S3', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'Vector instructions aimed at on-device inference.' },
      { name: 'ESP32-C6', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'RISC-V with Wi-Fi 6, Thread and Zigbee.' },
      { name: 'ESP32-P4', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'High-performance RISC-V application class, no integrated radio.' },
      { name: 'ESP32-C3', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'ESP32-H2', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'ESP32-S2', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30' },
      { name: 'ESP32 (original)', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30' },
    ],
    keywords: ['esp32', 'wifi', 'bluetooth', 'risc-v', 'xtensa', 'esp-idf', 'espressif'],
  },
  {
    id: 'ent-esp8266',
    slug: 'espressif-esp8266',
    name: 'Espressif ESP8266',
    aliases: ['ESP8266', 'NodeMCU', 'Wemos D1'],
    kind: 'hardware-family',
    vendorOrOwner: 'Espressif Systems',
    familyId: 'ent-esp32',
    pillarIds: ['compute', 'networks'],
    domainIds: ['firmware', 'iiot'],
    categoryIds: ['hardware-family', 'legacy-reference'],
    summary:
      'The Wi-Fi microcontroller that preceded ESP32, still in wide circulation on NodeMCU and Wemos D1 development boards but superseded for new designs.',
    useCases: ['Simple Wi-Fi telemetry where the ESP32 feature set is unnecessary'],
    lifecycle: 'legacy',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: ['src-espressif'],
    coverageKind: 'ecosystem-reference',
    models: [
      { name: 'NodeMCU', lifecycle: 'legacy', lifecycleAsOf: '2026-07-30' },
      { name: 'Wemos D1', lifecycle: 'legacy', lifecycleAsOf: '2026-07-30' },
    ],
    keywords: ['esp8266', 'nodemcu', 'wemos', 'wifi', 'legacy'],
  },
  {
    id: 'ent-esp-now',
    slug: 'esp-now',
    name: 'ESP-NOW',
    aliases: ['ESP-NOW', 'ESP-NOW kits'],
    kind: 'protocol',
    vendorOrOwner: 'Espressif Systems',
    pillarIds: ['networks'],
    domainIds: ['iiot'],
    categoryIds: ['protocol'],
    summary:
      'A connectionless Espressif link protocol that lets ESP devices exchange short frames directly without joining a Wi-Fi network, used for low-latency peer-to-peer links.',
    useCases: ['Low-latency remote control between two ESP nodes', 'Mesh-style sensor reporting without an access point'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: ['src-espressif'],
    coverageKind: 'ecosystem-reference',
    keywords: ['esp-now', 'peer to peer', 'wireless', 'low latency'],
  },

  {
    id: 'ent-stm32',
    slug: 'stm32',
    name: 'STMicroelectronics STM32',
    aliases: ['STM32', 'STM32F4', 'STM32H7', 'STM32G4', 'STM32 Nucleo', 'STM32U5', 'STM32N6'],
    kind: 'hardware-family',
    vendorOrOwner: 'STMicroelectronics',
    pillarIds: ['compute', 'electronics'],
    domainIds: ['firmware', 'realtime', 'power-electronics'],
    categoryIds: ['hardware-family', 'electronic-component'],
    summary:
      'A very broad Arm Cortex-M microcontroller family covering ultra-low-power, mainstream, high-performance and wireless lines, with Nucleo and Discovery evaluation boards across the range.',
    useCases: [
      'Motor control and power conversion on the G4 and F3 lines',
      'Real-time firmware with tight interrupt latency budgets',
      'Low-power battery devices on the L and U lines',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: ['src-st'],
    coverageKind: 'ecosystem-reference',
    models: [
      { name: 'STM32H7', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'STM32U5', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'Ultra-low-power line.' },
      { name: 'STM32G4', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'Mixed-signal, aimed at motor control and conversion.' },
      { name: 'STM32G0', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'STM32N6', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'Adds a neural processing unit for edge inference.' },
      { name: 'STM32WB', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'Bluetooth LE and 802.15.4.' },
      { name: 'STM32WL', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'Integrated sub-GHz LoRa radio.' },
      { name: 'STM32L4', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30' },
      { name: 'STM32L0', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30' },
      { name: 'STM32F7', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30' },
      { name: 'STM32F4', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30' },
      { name: 'STM32F3', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30' },
      { name: 'STM32F1', lifecycle: 'legacy', lifecycleAsOf: '2026-07-30' },
      { name: 'STM32F0', lifecycle: 'legacy', lifecycleAsOf: '2026-07-30' },
      { name: 'STM8', lifecycle: 'legacy', lifecycleAsOf: '2026-07-30', note: '8-bit line, separate from the Arm STM32 family.' },
    ],
    keywords: ['stm32', 'cortex-m', 'nucleo', 'discovery', 'hal', 'cubemx', 'stmicroelectronics'],
  },

  {
    id: 'ent-beagleboard',
    slug: 'beagleboard',
    name: 'BeagleBoard and BeagleBone',
    aliases: ['BeagleBone', 'BeagleBone Black', 'BeagleBoard', 'BeagleY-AI', 'BeagleV', 'BeagleBone AI-64', 'BeagleBone Blue'],
    kind: 'hardware-family',
    vendorOrOwner: 'BeagleBoard.org Foundation',
    pillarIds: ['compute', 'controls', 'ai'],
    domainIds: ['firmware', 'realtime', 'edge-ai'],
    categoryIds: ['hardware-family'],
    summary:
      'Open-hardware Linux boards notable for the programmable real-time units on the TI Sitara parts, which give deterministic I/O alongside a general-purpose Linux core.',
    useCases: [
      'Deterministic motion or protocol I/O on the PRU while Linux handles the rest',
      'Open-hardware robotics controller with on-board motor and IMU support',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: ['src-beagleboard'],
    coverageKind: 'ecosystem-reference',
    models: [
      { name: 'BeagleY-AI', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'TI AM67A based, Pi-format board with an on-chip AI accelerator.' },
      { name: 'BeagleV-Ahead', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'RISC-V, T-Head TH1520.' },
      { name: 'BeagleV-Fire', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'RISC-V with a Microchip PolarFire SoC FPGA fabric.' },
      { name: 'BeagleBone AI-64', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'TI TDA4VM.' },
      { name: 'BeagleBone Black', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30' },
      { name: 'BeagleBone Black Wireless', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30' },
      { name: 'BeagleBone Blue', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30', note: 'Robotics variant with motor drivers, IMU and barometer on board.' },
      { name: 'BeagleBone Green', lifecycle: 'legacy', lifecycleAsOf: '2026-07-30', note: 'Seeed Studio variant.' },
      { name: 'BeagleV (original)', lifecycle: 'discontinued', lifecycleAsOf: '2026-07-30', note: 'The original BeagleV RISC-V prototype programme did not reach production.' },
    ],
    keywords: ['beaglebone', 'pru', 'sitara', 'risc-v', 'open hardware', 'polarfire'],
  },

  {
    id: 'ent-google-coral',
    slug: 'google-coral',
    name: 'Google Coral',
    aliases: ['Coral', 'Coral TPU', 'Edge TPU', 'Coral USB Accelerator', 'Coral Dev Board'],
    kind: 'hardware-family',
    vendorOrOwner: 'Google',
    pillarIds: ['ai', 'compute'],
    domainIds: ['edge-ai', 'architecture'],
    categoryIds: ['hardware-family', 'accelerator'],
    summary:
      'Edge TPU accelerators in USB, M.2, PCIe and development-board form, running quantised INT8 models compiled by the Edge TPU compiler.',
    useCases: [
      'Adding fixed-function INT8 inference to an existing Linux host',
      'Low-power always-on vision where a GPU is not justified',
    ],
    lifecycle: 'maintained',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: ['src-coral'],
    coverageKind: 'ecosystem-reference',
    models: [
      { name: 'Coral USB Accelerator', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30', note: 'First-generation Edge TPU over USB.' },
      { name: 'Coral Dev Board', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30' },
      { name: 'Coral M.2 and Mini PCIe accelerators', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30' },
      { name: 'Coral Dev Board Micro', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30' },
    ],
    keywords: ['coral', 'edge tpu', 'int8', 'quantisation', 'accelerator', 'litert'],
  },
  {
    id: 'ent-hailo',
    slug: 'hailo',
    name: 'Hailo AI accelerators',
    aliases: ['Hailo', 'Hailo-8', 'Hailo-8L', 'Hailo-10H', 'HailoRT'],
    kind: 'hardware-family',
    vendorOrOwner: 'Hailo',
    pillarIds: ['ai', 'compute'],
    domainIds: ['edge-ai', 'architecture'],
    categoryIds: ['hardware-family', 'accelerator'],
    summary:
      'Dataflow neural accelerators in M.2 and module form, used where sustained inference throughput per watt matters more than general-purpose compute. Also the silicon inside the Raspberry Pi AI accelerators.',
    useCases: [
      'Multi-stream video analytics on an embedded host',
      'Generative and vision-language workloads at the edge on the 10H',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: ['src-hailo', 'src-rpi-aihat'],
    coverageKind: 'ecosystem-reference',
    models: [
      { name: 'Hailo-10H', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'The accelerator inside the Raspberry Pi AI HAT+ 2, rated at 40 TOPS at INT4.' },
      { name: 'Hailo-8', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'Around 26 TOPS.' },
      { name: 'Hailo-8L', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'Around 13 TOPS entry variant.' },
    ],
    keywords: ['hailo', 'npu', 'tops', 'dataflow', 'inference', 'm.2'],
  },

  {
    id: 'ent-teensy',
    slug: 'teensy',
    name: 'Teensy',
    aliases: ['Teensy', 'Teensy 4.1', 'Teensy 4.0', 'Teensy 3.6', 'MicroMod Teensy'],
    kind: 'hardware-family',
    vendorOrOwner: 'PJRC',
    pillarIds: ['compute'],
    domainIds: ['firmware', 'realtime'],
    categoryIds: ['hardware-family'],
    summary:
      'Very compact high-clock microcontroller boards built on NXP i.MX RT crossover parts, favoured for audio, high-rate sampling and tight control loops in a small footprint.',
    useCases: ['High-rate deterministic sampling in a small board area', 'Real-time audio and signal processing'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    models: [
      { name: 'Teensy 4.1', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'Teensy 4.0', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'MicroMod Teensy', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'SparkFun MicroMod form factor.' },
      { name: 'Teensy 3.6', lifecycle: 'discontinued', lifecycleAsOf: '2026-07-30' },
      { name: 'Teensy 3.5', lifecycle: 'discontinued', lifecycleAsOf: '2026-07-30' },
      { name: 'Teensy 3.2', lifecycle: 'discontinued', lifecycleAsOf: '2026-07-30' },
    ],
    keywords: ['teensy', 'pjrc', 'i.mx rt', 'audio', 'high speed'],
  },
  {
    id: 'ent-seeed',
    slug: 'seeed-studio',
    name: 'Seeed Studio boards and modules',
    aliases: ['Seeed', 'Seeed Studio', 'XIAO', 'Seeed XIAO', 'reTerminal', 'Wio Terminal', 'ODYSSEY X86', 'Grove', 'SenseCAP'],
    kind: 'hardware-family',
    vendorOrOwner: 'Seeed Studio',
    pillarIds: ['compute', 'networks', 'ai'],
    domainIds: ['firmware', 'iiot', 'edge-ai'],
    categoryIds: ['hardware-family', 'sensor'],
    summary:
      'A broad catalogue of small boards, HMI terminals and the Grove connector ecosystem, including the thumbnail-sized XIAO line across several silicon vendors and the SenseCAP LoRaWAN sensor range.',
    useCases: [
      'Very small wireless sensor nodes on the XIAO footprint',
      'Solderless sensor prototyping through Grove connectors',
      'Ready-made industrial HMI terminal on Pi-class compute',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    models: [
      { name: 'XIAO ESP32-S3', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'XIAO ESP32-C3', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'XIAO nRF52840', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'XIAO RP2040', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'reTerminal', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'Wio Terminal', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'SenseCAP', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'LoRaWAN industrial sensor range.' },
      { name: 'Grove ecosystem', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'Standardised four-wire connector system for sensors and actuators.' },
      { name: 'ODYSSEY X86', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30' },
    ],
    keywords: ['seeed', 'xiao', 'grove', 'sensecap', 'reterminal', 'wio', 'lorawan'],
  },
  {
    id: 'ent-m5stack',
    slug: 'm5stack',
    name: 'M5Stack',
    aliases: ['M5Stack', 'M5Stack Core', 'Core2', 'CoreS3', 'M5Atom', 'M5Stamp'],
    kind: 'hardware-family',
    vendorOrOwner: 'M5Stack',
    pillarIds: ['compute', 'networks'],
    domainIds: ['firmware', 'iiot'],
    categoryIds: ['hardware-family'],
    summary:
      'Stackable ESP32 modules in finished enclosures with display, battery and expansion bus, used where a prototype needs to look and behave like a product immediately.',
    useCases: ['Rapid enclosed prototype with display and battery', 'Portable diagnostic or field tool'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    models: [
      { name: 'M5Stack CoreS3', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'M5Stack Core2', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'M5Stack Core', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30' },
      { name: 'M5Atom', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'M5Stamp', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
    ],
    keywords: ['m5stack', 'esp32', 'stackable', 'enclosed', 'display'],
  },

  {
    id: 'ent-alt-sbc',
    slug: 'alternative-single-board-computers',
    name: 'Alternative single-board computers',
    aliases: [
      'Orange Pi',
      'Banana Pi',
      'Radxa',
      'Radxa ROCK',
      'Rock Pi',
      'LattePanda',
      'Khadas',
      'Khadas VIM3',
      'Milk-V',
      'StarFive',
      'StarFive VisionFive 2',
      'Pine64',
      'RockPro64',
      'Quartz64',
      'Libre Computer',
    ],
    kind: 'hardware-family',
    vendorOrOwner: 'Various vendors',
    pillarIds: ['compute', 'ai'],
    domainIds: ['architecture', 'edge-ai'],
    categoryIds: ['hardware-family'],
    summary:
      'The wider single-board computer market beyond Raspberry Pi, largely built on Rockchip, Amlogic and Allwinner silicon, with a growing RISC-V segment and x86 options where Windows or Intel tooling is required.',
    useCases: [
      'Higher core count or NPU capability than a Pi at similar cost',
      'RISC-V software bring-up on real hardware',
      'x86 edge compute where an existing Windows application must run',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    models: [
      { name: 'Orange Pi 5, 5 Pro, 5 Plus, 3B, CM4', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'Largely Rockchip RK3588 class.' },
      { name: 'Radxa ROCK 3, 4 and 5', aliases: ['Rock Pi'], lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'Khadas VIM3 and VIM4', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'StarFive VisionFive 2', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'RISC-V.' },
      { name: 'Milk-V', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'RISC-V board range.' },
      { name: 'LattePanda V1, 3 Delta, Sigma', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'x86.' },
      { name: 'Banana Pi', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'Pine64 RockPro64 and Quartz64', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30' },
      { name: 'Libre Computer', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
    ],
    keywords: ['sbc', 'rockchip', 'rk3588', 'risc-v', 'x86', 'orange pi', 'radxa', 'khadas', 'pine64'],
  },
  {
    id: 'ent-industrial-x86',
    slug: 'industrial-x86-edge-computers',
    name: 'Industrial x86 and edge computers',
    aliases: ['Intel NUC', 'UP Squared', 'UP Xtreme', 'SIMATIC IOT2040', 'SIMATIC IOT2050', 'Siemens IOT2000', 'Advantech', 'Dell Edge Gateway'],
    kind: 'hardware-family',
    vendorOrOwner: 'Various vendors',
    pillarIds: ['networks', 'ot'],
    domainIds: ['iiot', 'industrial-automation'],
    categoryIds: ['hardware-family', 'vendor-platform'],
    summary:
      'Fanless industrial PCs, DIN-rail gateways and small-form x86 machines used as edge compute in plants, with extended temperature ranges and defined supply lifetimes.',
    useCases: [
      'Protocol translation and buffering between OT and IT networks',
      'On-premise analytics next to the line rather than in a data centre',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    models: [
      { name: 'Siemens SIMATIC IOT2050', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'Siemens SIMATIC IOT2040', lifecycle: 'legacy', lifecycleAsOf: '2026-07-30' },
      { name: 'UP Squared and UP Xtreme', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'Advantech industrial gateways', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'Dell Edge Gateway', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'Intel NUC', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30', note: 'The NUC product line transferred from Intel to ASUS.' },
    ],
    keywords: ['edge gateway', 'industrial pc', 'din rail', 'fanless', 'simatic', 'nuc'],
  },
] as const
