import type { EcosystemEntity } from '../types'

/** Microcontroller, processor, FPGA and accelerator silicon families. */
export const siliconEntities: readonly EcosystemEntity[] = [
  {
    id: 'ent-nxp-mcu',
    slug: 'nxp-microcontrollers',
    name: 'NXP microcontrollers and processors',
    aliases: ['NXP', 'i.MX RT', 'i.MX', 'LPC', 'S32K', 'Kinetis', 'Layerscape', 'NXP eIQ'],
    kind: 'hardware-family',
    vendorOrOwner: 'NXP Semiconductors',
    pillarIds: ['compute', 'electronics'],
    domainIds: ['firmware', 'realtime', 'architecture'],
    categoryIds: ['hardware-family', 'electronic-component'],
    summary:
      'A range spanning i.MX RT crossover microcontrollers, i.MX application processors, general-purpose LPC and Kinetis parts, and the automotive-qualified S32K line.',
    useCases: [
      'Crossover parts where MCU determinism and MPU throughput are both required',
      'Automotive body and chassis controllers on S32K',
      'Edge inference through the eIQ machine learning environment',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    models: [
      { name: 'i.MX RT 10xx and 11xx', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'i.MX 8 and i.MX 9', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'i.MX 8M Plus and i.MX 9 carry an NPU for edge inference.' },
      { name: 'S32K', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'LPC', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30' },
      { name: 'Layerscape', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'i.MX 6 and i.MX 7', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30' },
      { name: 'Kinetis', lifecycle: 'legacy', lifecycleAsOf: '2026-07-30' },
    ],
    keywords: ['nxp', 'imx', 'crossover', 's32k', 'automotive', 'eiq', 'npu'],
  },
  {
    id: 'ent-ti-mcu',
    slug: 'ti-microcontrollers',
    name: 'Texas Instruments microcontrollers and processors',
    aliases: ['TI C2000', 'MSP430', 'MSP432', 'Tiva C', 'Sitara', 'AM243x', 'AM62x', 'Jacinto', 'TDA4x', 'TI C6x', 'C2000 Delfino'],
    kind: 'hardware-family',
    vendorOrOwner: 'Texas Instruments',
    pillarIds: ['compute', 'electronics', 'controls'],
    domainIds: ['firmware', 'power-electronics', 'realtime', 'architecture'],
    categoryIds: ['hardware-family', 'electronic-component'],
    summary:
      'Real-time control microcontrollers (C2000), low-power MSP parts, Sitara application processors and Jacinto automotive processors, with C6x digital signal processors alongside.',
    useCases: [
      'High-frequency motor control and power conversion loops on C2000',
      'Ultra-low-power measurement on MSP430',
      'Automotive perception on Jacinto TDA4x',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    models: [
      { name: 'C2000 F28004x, F2837x, F2838x, F28P55x', aliases: ['C2000 Delfino'], lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'Sitara AM243x and AM62x', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'Jacinto TDA4x', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'MSP430', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30' },
      { name: 'C6x DSP', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30' },
      { name: 'MSP432', lifecycle: 'legacy', lifecycleAsOf: '2026-07-30' },
      { name: 'Tiva C', lifecycle: 'legacy', lifecycleAsOf: '2026-07-30' },
    ],
    keywords: ['texas instruments', 'c2000', 'msp430', 'sitara', 'jacinto', 'dsp', 'motor control'],
  },
  {
    id: 'ent-microchip-mcu',
    slug: 'microchip-microcontrollers',
    name: 'Microchip microcontrollers',
    aliases: ['Microchip', 'PIC', 'dsPIC', 'AVR', 'ATmega', 'ATtiny', 'SAM', 'SAMD21', 'SAMD51', 'PIC32'],
    kind: 'hardware-family',
    vendorOrOwner: 'Microchip Technology',
    pillarIds: ['compute'],
    domainIds: ['firmware'],
    categoryIds: ['hardware-family', 'electronic-component'],
    summary:
      'The PIC and dsPIC lines alongside the AVR parts acquired with Atmel and the Arm Cortex-M SAM families, covering 8-bit through 32-bit.',
    useCases: [
      'Cost-sensitive 8-bit control where an Arm core is unnecessary',
      'Digital signal control on dsPIC for power and motor applications',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    models: [
      { name: 'SAM D, E, S and V', aliases: ['SAMD21', 'SAMD51'], lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'dsPIC', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'PIC32', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'AVR ATmega and ATtiny', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30', note: 'ATmega328P is the microcontroller on the classic Arduino UNO R3.' },
      { name: 'PIC8 and PIC16', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30' },
    ],
    keywords: ['microchip', 'pic', 'avr', 'atmega', 'attiny', 'sam', 'atmel', '8-bit'],
  },
  {
    id: 'ent-renesas-mcu',
    slug: 'renesas-microcontrollers',
    name: 'Renesas microcontrollers',
    aliases: ['Renesas', 'Renesas RA', 'RA4M1', 'Renesas RX', 'RL78', 'e2 studio'],
    kind: 'hardware-family',
    vendorOrOwner: 'Renesas Electronics',
    pillarIds: ['compute'],
    domainIds: ['firmware'],
    categoryIds: ['hardware-family', 'electronic-component'],
    summary:
      'The Arm Cortex-M RA family alongside the proprietary RX and low-power RL78 cores. The RA4M1 is the part behind the Arduino UNO R4 and Nano R4.',
    useCases: ['General-purpose embedded control', 'Low-power industrial and appliance control on RL78'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: ['src-arduino-nano-r4'],
    coverageKind: 'ecosystem-reference',
    models: [
      { name: 'RA family', aliases: ['RA4M1'], lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'RX family', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'RL78 family', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
    ],
    keywords: ['renesas', 'ra4m1', 'rx', 'rl78', 'cortex-m'],
  },
  {
    id: 'ent-infineon-mcu',
    slug: 'infineon-microcontrollers',
    name: 'Infineon microcontrollers',
    aliases: ['Infineon', 'AURIX', 'TC2xx', 'TC3xx', 'TC4x', 'XMC', 'PSoC', 'Cypress', 'ModusToolbox', 'iMOTION'],
    kind: 'hardware-family',
    vendorOrOwner: 'Infineon Technologies',
    pillarIds: ['compute', 'electronics', 'safety'],
    domainIds: ['firmware', 'realtime', 'functional-safety', 'power-electronics'],
    categoryIds: ['hardware-family', 'electronic-component'],
    summary:
      'AURIX multicore automotive safety controllers, the XMC industrial line, and the PSoC configurable mixed-signal parts acquired with Cypress.',
    useCases: [
      'Automotive controllers requiring lockstep cores and ASIL capability',
      'Motor control on the iMOTION platform',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    models: [
      { name: 'AURIX TC3xx and TC4x', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'AURIX TC2xx', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30' },
      { name: 'PSoC', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'XMC', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
    ],
    keywords: ['infineon', 'aurix', 'psoc', 'cypress', 'asil', 'lockstep', 'imotion'],
  },
  {
    id: 'ent-nordic-mcu',
    slug: 'nordic-semiconductor',
    name: 'Nordic Semiconductor nRF',
    aliases: ['Nordic', 'nRF52', 'nRF53', 'nRF54', 'nRF91', 'nRF51', 'nRF52840'],
    kind: 'hardware-family',
    vendorOrOwner: 'Nordic Semiconductor',
    pillarIds: ['compute', 'networks'],
    domainIds: ['firmware', 'iiot'],
    categoryIds: ['hardware-family', 'electronic-component'],
    summary:
      'Low-power wireless microcontrollers covering Bluetooth LE, Thread, Zigbee and Matter, with the nRF91 series adding LTE-M and NB-IoT cellular.',
    useCases: ['Battery-powered BLE sensors and wearables', 'Cellular IoT endpoints without a separate modem'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    models: [
      { name: 'nRF54', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'nRF53', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'nRF52 and nRF52840', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'nRF91', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'LTE-M and NB-IoT.' },
      { name: 'nRF51', lifecycle: 'legacy', lifecycleAsOf: '2026-07-30' },
    ],
    keywords: ['nordic', 'nrf52', 'ble', 'thread', 'matter', 'nb-iot', 'zephyr'],
  },
  {
    id: 'ent-riscv-silicon',
    slug: 'risc-v-silicon',
    name: 'RISC-V microcontrollers and processors',
    aliases: ['RISC-V', 'SiFive', 'GD32V', 'Bouffalo', 'BL602', 'BL702', 'T-Head', 'Kendryte', 'K210', 'K510'],
    kind: 'hardware-family',
    vendorOrOwner: 'Various vendors (RISC-V International ISA)',
    pillarIds: ['compute'],
    domainIds: ['firmware', 'architecture'],
    categoryIds: ['hardware-family', 'electronic-component'],
    summary:
      'Silicon built on the open RISC-V instruction set, from SiFive cores and GD32V microcontrollers to Bouffalo wireless parts and Kendryte AI-oriented designs.',
    useCases: [
      'Avoiding architecture licensing in a custom SoC',
      'Software bring-up and toolchain work on an open ISA',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    models: [
      { name: 'SiFive E, U and FE series', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'GD32V', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'Bouffalo BL602 and BL702', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'Kendryte K210 and K510', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30' },
    ],
    keywords: ['risc-v', 'sifive', 'open isa', 'gd32v', 'kendryte', 'bouffalo'],
  },
  {
    id: 'ent-ambiq',
    slug: 'ambiq-apollo',
    name: 'Ambiq Apollo',
    aliases: ['Ambiq', 'Apollo', 'Ambiq Apollo'],
    kind: 'hardware-family',
    vendorOrOwner: 'Ambiq Micro',
    pillarIds: ['compute', 'ai'],
    domainIds: ['firmware', 'edge-ai'],
    categoryIds: ['hardware-family', 'electronic-component'],
    summary:
      'Sub-threshold power microcontrollers built for always-on sensing and TinyML in energy budgets where conventional Cortex-M parts would not survive on a coin cell.',
    useCases: ['Always-on wearable sensing', 'Battery-decade endurance sensor nodes'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['ambiq', 'apollo', 'low power', 'always on', 'tinyml', 'subthreshold'],
  },
  {
    id: 'ent-arm-cores',
    slug: 'arm-processor-cores',
    name: 'Arm processor cores',
    aliases: ['ARM', 'Cortex-A', 'Cortex-R', 'Cortex-M', 'Neoverse', 'Mali', 'ARM Cortex'],
    kind: 'hardware-family',
    vendorOrOwner: 'Arm',
    pillarIds: ['compute'],
    domainIds: ['architecture', 'firmware', 'realtime'],
    categoryIds: ['hardware-family', 'electronic-component'],
    summary:
      'The licensed core families underneath most embedded silicon: Cortex-M for microcontrollers, Cortex-R for real-time, Cortex-A for application processors and Neoverse for server and infrastructure.',
    useCases: ['Selecting a core class against a determinism and throughput budget'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['arm', 'cortex-m', 'cortex-a', 'cortex-r', 'neoverse', 'mali', 'core ip'],
  },
  {
    id: 'ent-soc-mpu',
    slug: 'application-socs-and-mpus',
    name: 'Application SoCs and MPUs',
    aliases: ['Rockchip', 'RK3588', 'RK3399', 'RK3566', 'RK3568', 'Allwinner', 'Broadcom BCM2712', 'BCM2711', 'Qualcomm QCS', 'RB5', 'QRB5165', 'MediaTek Genio', 'Dragonwing', 'Apple silicon'],
    kind: 'hardware-family',
    vendorOrOwner: 'Various vendors',
    pillarIds: ['compute', 'ai'],
    domainIds: ['architecture', 'edge-ai'],
    categoryIds: ['hardware-family', 'electronic-component'],
    summary:
      'The application-class silicon inside single-board computers and smart devices, most carrying an integrated GPU and, increasingly, a neural processing unit.',
    useCases: ['Choosing board silicon by NPU capability and mainline Linux support'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    models: [
      { name: 'Rockchip RK3588 and RK3588S', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'Rockchip RK3566 and RK3568', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'Broadcom BCM2712', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'The Raspberry Pi 5 and Pi 500 application processor.' },
      { name: 'Qualcomm QCS, RB5, RB6 and QRB5165', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'Qualcomm Dragonwing QRB2210', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'The Linux-side processor on the Arduino UNO Q.' },
      { name: 'MediaTek Genio', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'Allwinner H3, H5, H6, A64 and D1', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30', note: 'D1 is RISC-V.' },
      { name: 'Broadcom BCM2711', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30', note: 'Raspberry Pi 4.' },
      { name: 'Rockchip RK3399 and RK3288', lifecycle: 'legacy', lifecycleAsOf: '2026-07-30' },
      { name: 'Apple silicon', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'Used for on-device machine learning research rather than as embedded robotics compute.' },
    ],
    keywords: ['soc', 'mpu', 'rockchip', 'allwinner', 'broadcom', 'qualcomm', 'mediatek', 'npu'],
  },

  {
    id: 'ent-amd-xilinx-fpga',
    slug: 'amd-xilinx-fpga',
    name: 'AMD (Xilinx) FPGAs and adaptive SoCs',
    aliases: ['Xilinx', 'AMD Xilinx', 'Zynq', 'Zynq-7000', 'Zynq UltraScale+', 'Versal', 'Artix-7', 'Spartan-7', 'Kintex-7', 'Virtex-7', 'RFSoC', 'PYNQ', 'ZedBoard', 'Zybo', 'Nexys A7', 'Basys 3', 'KV260', 'KR260', 'K26 SOM', 'Ultra96', 'Alinx AXU'],
    kind: 'hardware-family',
    vendorOrOwner: 'AMD',
    pillarIds: ['electronics', 'compute'],
    domainIds: ['microelectronics', 'architecture', 'realtime'],
    categoryIds: ['hardware-family', 'accelerator'],
    summary:
      'The largest FPGA and adaptive SoC family, spanning cost-optimised Spartan and Artix parts, the Zynq processor-plus-fabric devices and the Versal adaptive compute platform.',
    useCases: [
      'Hard real-time control loops implemented in fabric rather than software',
      'Custom sensor interfaces and line-rate signal processing',
      'Zynq designs where Arm cores and programmable logic share memory',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    models: [
      { name: 'Versal AI Core, Prime and Edge', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'Zynq UltraScale+ MPSoC and RFSoC', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'Kria K26 SOM, KV260 and KR260', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'Artix-7 and Spartan-7', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'Zynq-7000', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30' },
      { name: 'PYNQ-Z1 and PYNQ-Z2', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30', note: 'Development boards for the PYNQ Python framework.' },
      { name: 'ZedBoard, Zybo, Nexys A7, Basys 3, Ultra96, Alinx AXU', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30', note: 'Third-party development boards.' },
      { name: 'Kintex-7 and Virtex-7', lifecycle: 'legacy', lifecycleAsOf: '2026-07-30' },
    ],
    keywords: ['fpga', 'xilinx', 'amd', 'zynq', 'versal', 'vivado', 'vitis', 'rtl', 'kria'],
  },
  {
    id: 'ent-intel-altera-fpga',
    slug: 'intel-altera-fpga',
    name: 'Altera (Intel) FPGAs',
    aliases: ['Altera', 'Intel FPGA', 'Cyclone', 'Cyclone V', 'Cyclone IV', 'Cyclone 10', 'Arria', 'Stratix', 'Agilex', 'DE10-Nano', 'DE1-SoC', 'DE2-115', 'Terasic', 'SoCKit'],
    kind: 'hardware-family',
    vendorOrOwner: 'Altera',
    pillarIds: ['electronics', 'compute'],
    domainIds: ['microelectronics', 'architecture'],
    categoryIds: ['hardware-family', 'accelerator'],
    summary:
      'The Cyclone, Arria, Stratix and Agilex families, with the Cyclone V SoC parts widely used in education and in embedded designs needing Arm cores beside fabric.',
    useCases: ['Cost-sensitive fabric designs on Cyclone', 'High-bandwidth signal processing on Stratix and Agilex'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    models: [
      { name: 'Agilex', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'Cyclone 10', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'Stratix 10', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'Arria V and Arria 10', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30' },
      { name: 'Cyclone V', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30' },
      { name: 'DE10-Nano, DE10-Standard, DE1-SoC, DE2-115, SoCKit', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30', note: 'Terasic and Arrow development boards.' },
      { name: 'Cyclone IV', lifecycle: 'legacy', lifecycleAsOf: '2026-07-30' },
    ],
    keywords: ['fpga', 'altera', 'intel', 'cyclone', 'agilex', 'quartus', 'terasic'],
  },
  {
    id: 'ent-other-fpga',
    slug: 'lattice-microchip-gowin-efinix-fpga',
    name: 'Lattice, Microchip, Gowin and Efinix FPGAs',
    aliases: ['Lattice', 'iCE40', 'ECP5', 'CrossLink', 'CrossLink-NX', 'CertusPro-NX', 'iCEbreaker', 'TinyFPGA', 'ULX3S', 'Fomu', 'PolarFire', 'Icicle kit', 'Gowin', 'Tang Nano', 'Tang Primer', 'Efinix', 'Trion', 'Titanium'],
    kind: 'hardware-family',
    vendorOrOwner: 'Lattice, Microchip, Gowin, Efinix',
    pillarIds: ['electronics', 'compute'],
    domainIds: ['microelectronics', 'architecture'],
    categoryIds: ['hardware-family', 'accelerator'],
    summary:
      'The low-power and open-toolchain end of the FPGA market: Lattice iCE40 and ECP5 with fully open flows, Microchip PolarFire flash-based parts, and the newer Gowin and Efinix families.',
    useCases: [
      'Open-source synthesis and place-and-route without vendor tooling',
      'Low static power and instant-on designs on flash-based fabric',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    models: [
      { name: 'Lattice iCE40 UP, HX, LP and UL', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'Fully supported by the open Yosys and nextpnr flow.' },
      { name: 'Lattice ECP5', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'Lattice CrossLink, CrossLink-NX and CertusPro-NX', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'Microchip PolarFire and PolarFire SoC', aliases: ['Icicle kit'], lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'Gowin Tang Nano, Tang Mega and Tang Primer', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'Efinix Trion and Titanium', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'iCEbreaker, TinyFPGA, ULX3S, Fomu', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30', note: 'Open-hardware iCE40 and ECP5 development boards.' },
    ],
    keywords: ['fpga', 'lattice', 'ice40', 'ecp5', 'polarfire', 'gowin', 'efinix', 'yosys', 'nextpnr'],
  },
  {
    id: 'ent-asic',
    slug: 'asic-design',
    name: 'ASIC and custom silicon',
    aliases: ['ASIC', 'custom ASIC', 'standard cell', 'chiplets', 'HBM'],
    kind: 'hardware-family',
    vendorOrOwner: 'Various foundries and design houses',
    pillarIds: ['electronics'],
    domainIds: ['microelectronics'],
    categoryIds: ['electronic-component'],
    summary:
      'Application-specific integrated circuits: a full custom flow from RTL through standard-cell synthesis, place and route, and sign-off, justified only at volume or where no programmable part will meet the power or latency target.',
    useCases: ['Volume products where FPGA unit cost or power is prohibitive', 'Fixed-function accelerators'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['asic', 'standard cell', 'tapeout', 'chiplet', 'hbm', 'sign-off'],
  },
  {
    id: 'ent-gpu',
    slug: 'gpus',
    name: 'GPUs for training and inference',
    aliases: ['GPU', 'NVIDIA Ampere', 'Hopper', 'Blackwell', 'Mali', 'Adreno', 'NVLink', 'PCIe', 'CXL'],
    kind: 'hardware-family',
    vendorOrOwner: 'NVIDIA, Arm, Qualcomm and others',
    pillarIds: ['ai', 'compute'],
    domainIds: ['architecture', 'ml'],
    categoryIds: ['accelerator'],
    summary:
      'Massively parallel processors used for model training and high-throughput inference, connected by PCIe, NVLink or CXL fabrics, with mobile GPU families serving the embedded end.',
    useCases: ['Training perception models', 'Batch inference in a data centre or on a workstation'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    models: [
      { name: 'NVIDIA Blackwell', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'NVIDIA Hopper', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'NVIDIA Ampere', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30' },
      { name: 'Arm Mali', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'Qualcomm Adreno', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
    ],
    keywords: ['gpu', 'cuda', 'blackwell', 'hopper', 'ampere', 'nvlink', 'pcie', 'cxl', 'training'],
  },
  {
    id: 'ent-npu',
    slug: 'npus-and-dsps',
    name: 'NPUs, TPUs and DSPs',
    aliases: ['NPU', 'TPU', 'DSP', 'Qualcomm Hexagon', 'Intel Movidius', 'Myriad', 'Rockchip NPU', 'CEVA', 'Cadence Tensilica', 'Syntiant NDP', 'smart NIC', 'DPU'],
    kind: 'hardware-family',
    vendorOrOwner: 'Various vendors',
    pillarIds: ['ai', 'compute'],
    domainIds: ['architecture', 'edge-ai'],
    categoryIds: ['accelerator'],
    summary:
      'Fixed-function and semi-programmable accelerators for neural inference and signal processing, usually integrated into an SoC rather than sold as a discrete part.',
    useCases: ['Offloading inference from a constrained CPU', 'Always-on keyword and event detection at microwatt budgets'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    models: [
      { name: 'Qualcomm Hexagon', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'Rockchip NPU', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'CEVA and Cadence Tensilica DSP cores', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'Syntiant NDP', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'Intel Movidius Myriad', lifecycle: 'legacy', lifecycleAsOf: '2026-07-30' },
      { name: 'Intel Neural Compute Stick 2', aliases: ['NCS2'], lifecycle: 'discontinued', lifecycleAsOf: '2026-07-30', note: 'Discontinued. OpenVINO remains the supported path for Intel inference hardware.' },
    ],
    keywords: ['npu', 'tpu', 'dsp', 'hexagon', 'movidius', 'myriad', 'syntiant', 'inference'],
  },
] as const
