import type { EcosystemEntity } from '../types'

/** Functional safety, HRI, reliability, MBSE and systems-integration tooling. */
export const assuranceSoftwareEntities: readonly EcosystemEntity[] = [
  {
    id: 'ent-safety-analysis-tools',
    slug: 'functional-safety-analysis-tools',
    name: 'Functional safety analysis tools',
    aliases: ['SISTEMA', 'IFA tools', 'Pilz PAScal', 'PAScal', 'Medini Analyze', 'Ansys medini analyze', 'Siemens Safety Evaluation Tool', 'risk graph', 'SIL calculator', 'PL calculator'],
    kind: 'software',
    vendorOrOwner: 'IFA, Pilz, Ansys, Siemens',
    pillarIds: ['safety'],
    domainIds: ['functional-safety'],
    categoryIds: ['cad-cae', 'method'],
    summary:
      'Calculators and analysis environments that turn a safety architecture into a quantified performance level or safety integrity level, using published component reliability data.',
    useCases: [
      'Demonstrating a required performance level for a safety function',
      'Producing the calculation record an assessor will ask for',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: ['src-iso-13849-1'],
    coverageKind: 'ecosystem-reference',
    keywords: ['sistema', 'pascal', 'medini', 'performance level', 'sil', 'pfh', 'safety calculation'],
  },
  {
    id: 'ent-reliability-tools',
    slug: 'reliability-analysis-tools',
    name: 'Reliability analysis tools',
    aliases: ['ReliaSoft', 'Weibull++', 'BlockSim', 'RGA', 'ALTA', 'XFMEA', 'Isograph', 'FaultTree+', 'Reliability Workbench', 'APIS IQ', 'APIS IQ-RM', 'PTC Windchill Quality', 'Relex', 'MIL-HDBK-217', 'Telcordia', 'FRACAS'],
    kind: 'software',
    vendorOrOwner: 'Hottinger Brüel & Kjær ReliaSoft, Isograph, APIS, PTC',
    pillarIds: ['safety'],
    domainIds: ['reliability'],
    categoryIds: ['cad-cae', 'method'],
    summary:
      'Software for FMEA and FMECA, fault tree and reliability block diagram analysis, life-data fitting and prediction, and the corrective-action tracking that closes the loop from field failures.',
    useCases: [
      'Structured FMEA with traceable risk priority and actions',
      'Fitting a Weibull distribution to life-test data to predict a failure rate',
      'Modelling redundancy to compute system availability',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['reliasoft', 'weibull', 'fmea', 'fmeca', 'fault tree', 'rbd', 'mtbf', 'fracas', 'availability'],
  },
  {
    id: 'ent-ergonomics-tools',
    slug: 'ergonomics-and-human-factors-tools',
    name: 'Ergonomics and human factors tools',
    aliases: ['Siemens Jack', 'Jack', 'Delmia Human', 'Santos', 'RULA', 'REBA', 'NASA-TLX', 'digital human model'],
    kind: 'software',
    vendorOrOwner: 'Siemens, Dassault Systèmes and academic sources',
    pillarIds: ['safety', 'ot'],
    domainIds: ['hri', 'manufacturing'],
    categoryIds: ['cad-cae', 'method'],
    summary:
      'Digital human modelling and assessment methods that evaluate reach, posture, load and cognitive workload before a workstation is built rather than after an injury.',
    useCases: [
      'Checking reach and posture across a percentile range of operators',
      'Quantifying cognitive workload of a proposed interface',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['ergonomics', 'jack', 'delmia human', 'rula', 'reba', 'nasa-tlx', 'workload', 'posture'],
  },
  {
    id: 'ent-hri-software',
    slug: 'hri-software-stacks',
    name: 'HRI software stacks',
    aliases: ['ROS HRI', 'behavior tree HRI', 'gaze estimation', 'intent prediction', 'hand guiding', 'voice UI'],
    kind: 'framework',
    vendorOrOwner: 'Open-source projects and research groups',
    pillarIds: ['safety'],
    domainIds: ['hri'],
    categoryIds: ['framework', 'method'],
    summary:
      'Software for machines that work with people: perceiving where a person is looking and reaching, predicting intent, and structuring the interaction so the machine behaviour is legible.',
    useCases: ['Adapting robot speed to a person approaching', 'Voice or gesture instruction with a confirmation step'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['hri', 'intent prediction', 'gaze', 'behaviour tree', 'legibility', 'trust', 'voice ui'],
  },
  {
    id: 'ent-mbse',
    slug: 'mbse-and-sysml',
    name: 'MBSE and SysML tooling',
    aliases: ['SysML', 'UML', 'IBM Rhapsody', 'Rhapsody', 'Cameo', 'Cameo Systems Modeler', 'MagicDraw', 'No Magic', 'Capella', 'Enterprise Architect', 'PTC Windchill Modeler', 'ModelCenter', 'System Composer', 'MathWorks System Composer', 'MBSE'],
    kind: 'software',
    vendorOrOwner: 'IBM, Dassault Systèmes, Eclipse Foundation, Sparx Systems, MathWorks',
    pillarIds: ['safety'],
    domainIds: ['systems-integration'],
    categoryIds: ['cad-cae', 'method'],
    summary:
      'Model-based systems engineering environments where requirements, structure, behaviour and interfaces are one connected model rather than a set of documents that drift apart.',
    useCases: [
      'Tracing a requirement through architecture to a verification case',
      'Keeping interface definitions consistent across disciplines',
      'Trade studies evaluated against a shared model',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['sysml', 'mbse', 'rhapsody', 'cameo', 'capella', 'architecture', 'traceability', 'interfaces'],
  },
  {
    id: 'ent-requirements-alm',
    slug: 'requirements-and-lifecycle-management',
    name: 'Requirements and lifecycle management',
    aliases: ['DOORS', 'IBM DOORS', 'DOORS Next', 'Jama', 'Jama Connect', 'Polarion', 'Codebeamer', 'requirements management', 'ICD', 'interface control document', 'configuration management'],
    kind: 'software',
    vendorOrOwner: 'IBM, Jama Software, Siemens, PTC',
    pillarIds: ['safety'],
    domainIds: ['systems-integration', 'functional-safety'],
    categoryIds: ['platform', 'method'],
    summary:
      'Requirements capture with bidirectional traceability to design, test and defect records, which is what a regulated or safety-related project is audited against.',
    useCases: [
      'Proving every requirement has a verification result',
      'Impact analysis before accepting a change',
      'Baselining a configuration for a release',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['doors', 'jama', 'polarion', 'codebeamer', 'traceability', 'requirements', 'baseline', 'icd'],
  },
  {
    id: 'ent-plm',
    slug: 'plm-and-digital-thread',
    name: 'PLM and the digital thread',
    aliases: ['PLM', 'Teamcenter', 'Siemens Teamcenter', 'Windchill', 'PTC Windchill', '3DEXPERIENCE', 'Arena PLM', 'digital thread'],
    kind: 'vendor-platform',
    vendorOrOwner: 'Siemens, PTC, Dassault Systèmes, Arena',
    pillarIds: ['safety', 'ot'],
    domainIds: ['systems-integration', 'manufacturing'],
    categoryIds: ['platform'],
    summary:
      'Product lifecycle management holding the released bill of materials, revisions, change orders and effectivity, so what was built can be reconstructed years later.',
    useCases: ['Controlled engineering change across mechanical, electrical and software', 'As-built configuration for a delivered unit'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['plm', 'teamcenter', 'windchill', '3dexperience', 'bom', 'change order', 'revision', 'as-built'],
  },
  {
    id: 'ent-integration-middleware',
    slug: 'integration-and-api-middleware',
    name: 'Integration and API middleware',
    aliases: ['Kong', 'Apigee', 'API gateway', 'schema registry', 'Pact', 'contract testing', 'message broker'],
    kind: 'software',
    vendorOrOwner: 'Kong, Google, Pact Foundation',
    pillarIds: ['safety', 'networks'],
    domainIds: ['systems-integration', 'iiot'],
    categoryIds: ['framework', 'platform'],
    summary:
      'The plumbing between systems: gateways that own authentication and rate limiting, schema registries that version message formats, and contract testing that catches an interface break before deployment.',
    useCases: ['Versioning a telemetry schema without breaking consumers', 'Verifying a producer and consumer still agree'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['api gateway', 'kong', 'apigee', 'schema registry', 'pact', 'contract testing', 'versioning'],
  },
  {
    id: 'ent-testing-quality',
    slug: 'software-testing-and-code-quality',
    name: 'Software testing and code quality',
    aliases: ['Google Test', 'gtest', 'PyTest', 'ROS test framework', 'SonarQube', 'MISRA', 'MISRA C', 'MISRA C++', 'PC-lint', 'cppcheck', 'clang-tidy', 'ControlDesk', 'dSPACE ControlDesk', 'static analysis'],
    kind: 'software',
    vendorOrOwner: 'Google, SonarSource, MISRA, dSPACE and open-source projects',
    pillarIds: ['safety', 'compute'],
    domainIds: ['systems-integration', 'firmware'],
    categoryIds: ['ide-toolchain', 'method'],
    summary:
      'Unit and integration test frameworks, static analysis, and the coding-standard checkers required where a safety standard constrains language use.',
    useCases: [
      'Demonstrating MISRA compliance for a safety-related component',
      'Catching undefined behaviour before it reaches a target',
      'Automated regression across a control software release',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['gtest', 'pytest', 'sonarqube', 'misra', 'static analysis', 'lint', 'regression', 'coverage'],
  },
  {
    id: 'ent-project-management',
    slug: 'project-and-collaboration-tooling',
    name: 'Project and collaboration tooling',
    aliases: ['Jira', 'Confluence', 'Notion', 'Linear', 'Trello', 'Asana', 'MS Project', 'Draw.io', 'Lucidchart', 'Miro'],
    kind: 'software',
    vendorOrOwner: 'Atlassian, Notion, Microsoft and others',
    pillarIds: ['safety'],
    domainIds: ['systems-integration'],
    categoryIds: ['platform'],
    summary:
      'Issue tracking, documentation and diagramming used to run engineering delivery, and in regulated work often the record of who decided what and when.',
    useCases: ['Tracking commissioning punch lists to closure', 'Holding design rationale where the next engineer will find it'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['jira', 'confluence', 'notion', 'miro', 'draw.io', 'tracking', 'documentation', 'delivery'],
  },
  {
    id: 'ent-ux-tools',
    slug: 'interface-design-tools',
    name: 'Interface design tools',
    aliases: ['Figma', 'Adobe XD', 'Sketch', 'UX prototyping'],
    kind: 'software',
    vendorOrOwner: 'Figma, Adobe',
    pillarIds: ['safety'],
    domainIds: ['hri'],
    categoryIds: ['platform'],
    summary:
      'Interface design and prototyping tools, used for operator screens and machine HMIs where layout and information hierarchy affect how quickly a fault is understood.',
    useCases: ['Prototyping an operator screen before building it in the SCADA package'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['figma', 'adobe xd', 'sketch', 'prototype', 'hmi design', 'information hierarchy'],
  },
  {
    id: 'ent-quality-methods',
    slug: 'quality-and-improvement-methods',
    name: 'Quality and improvement methods',
    aliases: ['Six Sigma', 'DMAIC', 'lean', '5S', 'Kaizen', 'SMED', 'Kanban', 'value stream mapping', 'line balancing', 'takt time', 'OEE', 'theory of constraints', 'TOC', 'SPC', 'MTM', 'MOST', 'DFM', 'DFA', 'Kepner-Tregoe', 'HAZOP', 'HAZID', '8D'],
    kind: 'method',
    pillarIds: ['ot', 'safety'],
    domainIds: ['manufacturing', 'reliability', 'functional-safety'],
    categoryIds: ['method'],
    summary:
      'Structured improvement and analysis methods: lean and Six Sigma for throughput and variation, hazard studies for process risk, and disciplined root-cause approaches for problem solving.',
    useCases: [
      'Finding and relieving the constraint that actually limits output',
      'Systematic hazard identification across a process',
      'Structured root-cause investigation with verified corrective action',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['lean', 'six sigma', 'dmaic', 'oee', 'takt', 'hazop', 'spc', 'kaizen', 'root cause', '8d'],
  },
  {
    id: 'ent-commissioning-methods',
    slug: 'commissioning-and-verification-methods',
    name: 'Commissioning and verification methods',
    aliases: ['FAT', 'SAT', 'factory acceptance test', 'site acceptance test', 'V-model', 'V&V', 'verification and validation', 'ITP', 'inspection test plan', 'MDR', 'manufacturing data report', 'GAMP 5', 'trade study', 'hand-eye calibration'],
    kind: 'method',
    pillarIds: ['safety', 'ot'],
    domainIds: ['systems-integration', 'workcell'],
    categoryIds: ['method'],
    summary:
      'The structured proving of a delivered system: acceptance testing at works and on site, the V-model relationship between specification and test, and the documentation packages that constitute handover.',
    useCases: [
      'Proving a system against its specification before shipping',
      'Structured handover documentation for a regulated plant',
      'Registering a robot to the real cell geometry',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['fat', 'sat', 'v-model', 'verification', 'validation', 'itp', 'gamp 5', 'handover', 'commissioning'],
  },
] as const
