import type { EcosystemEntity } from '../types'

/** RTOSs, embedded toolchains, firmware libraries, real-time and acceleration software. */
export const embeddedSoftwareEntities: readonly EcosystemEntity[] = [
  {
    id: 'ent-freertos',
    slug: 'freertos',
    name: 'FreeRTOS',
    aliases: ['FreeRTOS'],
    kind: 'rtos',
    vendorOrOwner: 'Amazon Web Services',
    pillarIds: ['compute'],
    domainIds: ['firmware', 'realtime'],
    categoryIds: ['os-rtos'],
    summary:
      'A small preemptive real-time kernel that is close to the default choice on Cortex-M class parts, providing tasks, queues and timers without imposing a wider platform.',
    useCases: ['Structuring firmware as tasks with priorities rather than one superloop', 'Meeting deadlines on a constrained MCU'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: ['src-freertos'],
    coverageKind: 'ecosystem-reference',
    keywords: ['freertos', 'rtos', 'kernel', 'tasks', 'preemptive', 'cortex-m'],
  },
  {
    id: 'ent-zephyr',
    slug: 'zephyr',
    name: 'Zephyr',
    aliases: ['Zephyr', 'Zephyr RTOS', 'Zephyr SDK'],
    kind: 'rtos',
    vendorOrOwner: 'Linux Foundation',
    pillarIds: ['compute', 'networks'],
    domainIds: ['firmware', 'realtime', 'iiot'],
    categoryIds: ['os-rtos'],
    summary:
      'A scalable RTOS with a Linux-style build and configuration system, a large in-tree driver set and networking and Bluetooth stacks maintained alongside the kernel.',
    useCases: [
      'Portable firmware across several silicon vendors',
      'Connected devices needing a maintained BLE or IP stack',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: ['src-zephyr'],
    coverageKind: 'ecosystem-reference',
    keywords: ['zephyr', 'rtos', 'devicetree', 'kconfig', 'west', 'ble', 'portable'],
  },
  {
    id: 'ent-threadx',
    slug: 'eclipse-threadx',
    name: 'Eclipse ThreadX',
    aliases: ['ThreadX', 'Azure RTOS', 'Azure RTOS ThreadX', 'Eclipse ThreadX'],
    kind: 'rtos',
    vendorOrOwner: 'Eclipse Foundation',
    pillarIds: ['compute'],
    domainIds: ['firmware', 'realtime'],
    categoryIds: ['os-rtos'],
    summary:
      'A safety-certified real-time kernel with its middleware stacks, contributed by Microsoft to the Eclipse Foundation and renamed from Azure RTOS. The ThreadX Alliance was launched in October 2024 to sustain it.',
    useCases: ['Certified real-time software where a pre-certified kernel shortens the safety argument'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: ['src-threadx'],
    coverageKind: 'ecosystem-reference',
    keywords: ['threadx', 'azure rtos', 'eclipse', 'safety certified', 'rtos', 'netx', 'filex'],
  },
  {
    id: 'ent-commercial-rtos',
    slug: 'commercial-and-safety-rtos',
    name: 'Commercial and safety-critical RTOSs',
    aliases: ['VxWorks', 'QNX', 'Integrity', 'Green Hills Integrity', 'PikeOS', 'VxWorks MILS', 'embOS', 'Keil RTX5', 'TI-RTOS', 'micro-C/OS', 'uC/OS', 'QNX Hypervisor'],
    kind: 'rtos',
    vendorOrOwner: 'Wind River, BlackBerry QNX, Green Hills, SYSGO and others',
    pillarIds: ['compute', 'safety'],
    domainIds: ['realtime', 'firmware', 'functional-safety'],
    categoryIds: ['os-rtos'],
    summary:
      'Certified commercial real-time operating systems used where an assessor needs evidence, with partitioning and hypervisor variants that isolate mixed-criticality software on one processor.',
    useCases: [
      'Avionics, rail and medical software needing certification artefacts',
      'Running safety and non-safety workloads on shared silicon under partitioning',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['vxworks', 'qnx', 'integrity', 'pikeos', 'certification', 'partitioning', 'mixed criticality'],
  },
  {
    id: 'ent-open-rtos',
    slug: 'other-open-rtos',
    name: 'Other open real-time kernels',
    aliases: ['RT-Thread', 'NuttX', 'Tock', 'Apache NuttX'],
    kind: 'rtos',
    vendorOrOwner: 'Open-source projects',
    pillarIds: ['compute'],
    domainIds: ['firmware', 'realtime'],
    categoryIds: ['os-rtos'],
    summary:
      'Open kernels with distinct positions: NuttX offering a POSIX-like interface on small hardware, RT-Thread with a large component ecosystem, and Tock providing memory isolation through Rust.',
    useCases: ['POSIX-style portability on a microcontroller', 'Isolating untrusted application code on an MCU'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['nuttx', 'rt-thread', 'tock', 'posix', 'rust', 'open source rtos'],
  },
  {
    id: 'ent-rt-linux',
    slug: 'real-time-linux',
    name: 'Real-time Linux',
    aliases: ['PREEMPT_RT', 'RT Linux', 'Xenomai', 'RTAI', 'real-time Linux', 'cyclictest'],
    kind: 'os',
    vendorOrOwner: 'Linux kernel community',
    pillarIds: ['compute'],
    domainIds: ['realtime'],
    categoryIds: ['os-rtos'],
    summary:
      'Linux configured for bounded latency, principally through the PREEMPT_RT preemption model, with the co-kernel approaches of Xenomai and RTAI as alternatives where harder guarantees are needed.',
    useCases: [
      'Running a motion or EtherCAT master loop on Linux with bounded jitter',
      'Measuring achievable latency on real hardware before committing',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['preempt_rt', 'xenomai', 'rtai', 'latency', 'jitter', 'cyclictest', 'determinism'],
  },
  {
    id: 'ent-embedded-linux-build',
    slug: 'embedded-linux-build-systems',
    name: 'Embedded Linux build systems',
    aliases: ['Yocto', 'Yocto Project', 'Buildroot', 'OpenEmbedded', 'Balena', 'Android', 'AOSP', 'Windows IoT'],
    kind: 'os',
    vendorOrOwner: 'Yocto Project, Buildroot project and others',
    pillarIds: ['compute'],
    domainIds: ['firmware', 'architecture'],
    categoryIds: ['os-rtos', 'ide-toolchain'],
    summary:
      'Toolchains that produce a reproducible Linux image for a specific device, with the licence manifests, update mechanism and long-term maintainability a product needs.',
    useCases: ['Building a minimal, reproducible root filesystem for a product', 'Managing licence compliance across a Linux image'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['yocto', 'buildroot', 'openembedded', 'bitbake', 'reproducible', 'rootfs', 'aosp'],
  },
  {
    id: 'ent-embedded-ides',
    slug: 'embedded-ides-and-toolchains',
    name: 'Embedded IDEs and toolchains',
    aliases: ['STM32CubeIDE', 'Keil', 'Keil MDK', 'Keil uVision', 'IAR', 'IAR Embedded Workbench', 'PlatformIO', 'Arduino IDE', 'ESP-IDF', 'MCUXpresso', 'MPLAB X', 'Code Composer Studio', 'ModusToolbox', 'S32 Design Studio', 'AURIX Development Studio', 'Simplicity Studio', 'Atmel Studio', 'GCC for ARM', 'LLVM', 'Clang', 'CubeMX'],
    kind: 'software',
    vendorOrOwner: 'STMicroelectronics, Arm, IAR, Espressif, NXP, Microchip, TI and others',
    pillarIds: ['compute'],
    domainIds: ['firmware'],
    categoryIds: ['ide-toolchain'],
    summary:
      'Vendor and vendor-neutral development environments, including the certified commercial compilers used where a safety standard requires a qualified toolchain.',
    useCases: [
      'Configuring clocks and peripherals through a vendor generator',
      'Building the same project across boards and vendors from one environment',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['cubeide', 'keil', 'iar', 'platformio', 'esp-idf', 'mplab', 'ccs', 'gcc', 'toolchain'],
  },
  {
    id: 'ent-firmware-libraries',
    slug: 'firmware-libraries-and-stacks',
    name: 'Firmware libraries and stacks',
    aliases: ['CMSIS', 'CMSIS-DSP', 'CMSIS-NN', 'HAL', 'LL drivers', 'LVGL', 'lwIP', 'mbed TLS', 'TinyUSB', 'LUFA', 'FatFS', 'LittleFS', 'NanoPB', 'Particle Device OS', 'Arduino libraries', 'micro-ROS'],
    kind: 'library',
    vendorOrOwner: 'Arm, open-source projects and silicon vendors',
    pillarIds: ['compute'],
    domainIds: ['firmware'],
    categoryIds: ['framework'],
    summary:
      'The reusable layers inside firmware: hardware abstraction, filesystems, USB and IP stacks, TLS, embedded GUI and serialisation, so a project is not rewriting solved problems.',
    useCases: ['Adding a filesystem with wear levelling to on-board flash', 'Bringing up USB device classes without writing a stack'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['cmsis', 'lvgl', 'lwip', 'mbedtls', 'tinyusb', 'littlefs', 'nanopb', 'hal', 'micro-ros'],
  },
  {
    id: 'ent-embedded-languages',
    slug: 'embedded-scripting-languages',
    name: 'MicroPython and CircuitPython',
    aliases: ['MicroPython', 'CircuitPython'],
    kind: 'language',
    vendorOrOwner: 'MicroPython project, Adafruit',
    pillarIds: ['compute'],
    domainIds: ['firmware'],
    categoryIds: ['language'],
    summary:
      'Python implementations that run on the microcontroller itself, trading execution speed for a very short edit-and-test cycle during bring-up and teaching.',
    useCases: ['Rapid hardware bring-up without a compile and flash cycle', 'Teaching embedded concepts in a familiar language'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['micropython', 'circuitpython', 'repl', 'scripting', 'prototyping'],
  },
  {
    id: 'ent-realtime-tools',
    slug: 'real-time-analysis-tools',
    name: 'Real-time analysis and tracing tools',
    aliases: ['ftrace', 'LTTng', 'oslat', 'Chrony', 'PTPd', 'Tracy', 'perf', 'eBPF', 'bpftrace', 'VTune', 'Valgrind', 'GDB', 'OpenOCD', 'AddressSanitizer'],
    kind: 'software',
    vendorOrOwner: 'Open-source projects and Intel',
    pillarIds: ['compute'],
    domainIds: ['realtime', 'firmware'],
    categoryIds: ['ide-toolchain', 'test-measurement'],
    summary:
      'Tracing, profiling and clock-synchronisation tools used to measure latency and jitter rather than assume them, and to find where time is actually being spent.',
    useCases: [
      'Measuring worst-case scheduling latency under load',
      'Synchronising clocks across nodes for a sequence of events',
      'Finding a memory error before it becomes an intermittent field fault',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['ftrace', 'lttng', 'perf', 'ebpf', 'ptp', 'latency', 'profiling', 'sanitizer'],
  },
  {
    id: 'ent-hypervisors',
    slug: 'real-time-hypervisors',
    name: 'Real-time hypervisors',
    aliases: ['Jailhouse', 'ACRN', 'QNX Hypervisor', 'hypervisor', 'partitioning'],
    kind: 'software',
    vendorOrOwner: 'Siemens, Linux Foundation, BlackBerry QNX',
    pillarIds: ['compute'],
    domainIds: ['realtime', 'architecture'],
    categoryIds: ['os-rtos'],
    summary:
      'Partitioning hypervisors that run a real-time and a general-purpose operating system on one multicore device with spatial and temporal isolation between them.',
    useCases: ['Consolidating a controller and an HMI onto one SoC without losing determinism'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['jailhouse', 'acrn', 'hypervisor', 'partitioning', 'isolation', 'consolidation'],
  },
  {
    id: 'ent-autosar-os',
    slug: 'autosar-and-osek',
    name: 'AUTOSAR and OSEK',
    aliases: ['AUTOSAR', 'AUTOSAR OS', 'AUTOSAR Classic', 'AUTOSAR Adaptive', 'OSEK', 'ARINC 653'],
    kind: 'framework',
    vendorOrOwner: 'AUTOSAR partnership',
    pillarIds: ['compute', 'safety'],
    domainIds: ['realtime', 'functional-safety'],
    categoryIds: ['framework', 'standard'],
    summary:
      'Automotive software architecture standards defining a layered platform and timing model, with the Classic platform for deeply embedded ECUs and the Adaptive platform for high-performance compute.',
    useCases: ['Structuring automotive ECU software to a supplier-portable architecture'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: ['src-autosar'],
    coverageKind: 'ecosystem-reference',
    keywords: ['autosar', 'osek', 'arinc 653', 'automotive', 'ecu', 'timing model', 'classic', 'adaptive'],
  },
  {
    id: 'ent-gpu-compute',
    slug: 'gpu-and-accelerator-programming',
    name: 'GPU and accelerator programming',
    aliases: ['CUDA', 'cuDNN', 'cuBLAS', 'ROCm', 'OpenCL', 'SYCL', 'oneAPI', 'OpenVX', 'NNAPI', 'OpenAI Triton', 'Triton language'],
    kind: 'framework',
    vendorOrOwner: 'NVIDIA, AMD, Khronos Group, Intel, OpenAI',
    pillarIds: ['compute', 'ai'],
    domainIds: ['architecture', 'edge-ai'],
    categoryIds: ['framework', 'ide-toolchain'],
    summary:
      'Programming models for parallel accelerators, from the vendor-specific CUDA and ROCm stacks to the portable Khronos APIs and the Triton language for writing GPU kernels in Python.',
    useCases: [
      'Writing a custom kernel where a library primitive does not fit',
      'Portable acceleration across more than one vendor',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    models: [
      {
        name: 'OpenAI Triton',
        lifecycle: 'current',
        lifecycleAsOf: '2026-07-30',
        note: 'A language and compiler for GPU kernels. Distinct from the NVIDIA Triton Inference Server, which is a model-serving product and is catalogued separately.',
      },
      { name: 'CUDA, cuDNN and cuBLAS', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'ROCm', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'OpenCL and SYCL/oneAPI', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'OpenVX and NNAPI', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30' },
    ],
    keywords: ['cuda', 'opencl', 'sycl', 'rocm', 'triton', 'kernel', 'parallel', 'oneapi'],
  },
  {
    id: 'ent-embedded-buses',
    slug: 'embedded-buses-and-interfaces',
    name: 'Embedded buses and interfaces',
    aliases: ['SPI', 'I2C', 'UART', 'USART', 'CAN', 'CAN FD', 'CAN bus', 'LIN', '1-Wire', 'QSPI', 'USB', 'Ethernet MAC', 'JTAG', 'SWD', 'CSI-2', 'MIPI CSI-2', 'DSI', 'MIPI DSI', 'PCIe', 'I3C'],
    kind: 'protocol',
    vendorOrOwner: 'MIPI Alliance, Bosch, USB-IF, PCI-SIG and others',
    pillarIds: ['compute', 'electronics'],
    domainIds: ['firmware', 'instrumentation'],
    categoryIds: ['protocol'],
    summary:
      'The board and chip-level interfaces firmware actually talks over: simple synchronous and asynchronous serial links, the automotive CAN family, and the high-speed camera, display and expansion interfaces.',
    useCases: [
      'Choosing a sensor interface against distance, speed and pin count',
      'Attaching a camera over CSI-2 rather than USB for latency',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    models: [
      {
        name: 'MIPI CSI-2',
        aliases: ['MIPI', 'CSI-2'],
        lifecycle: 'current',
        lifecycleAsOf: '2026-07-30',
        note: 'The camera serial interface. Listed by specification rather than as generic "MIPI", which names the alliance and many unrelated specifications.',
      },
      { name: 'MIPI DSI', aliases: ['DSI'], lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'The display serial interface.' },
      { name: 'CAN and CAN FD', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'SPI, I2C, UART, 1-Wire, QSPI', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'JTAG and SWD', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
    ],
    keywords: ['spi', 'i2c', 'uart', 'can', 'lin', 'csi-2', 'dsi', 'jtag', 'swd', 'usb', 'pcie'],
  },
] as const
