import type { EcosystemEntity } from '../types'

/** Control design, robotics middleware, perception, SLAM and navigation software. */
export const roboticsSoftwareEntities: readonly EcosystemEntity[] = [
  {
    id: 'ent-matlab',
    slug: 'matlab',
    name: 'MATLAB',
    aliases: ['MATLAB', 'MATLAB script', 'Control System Toolbox', 'System Identification Toolbox', 'Robust Control Toolbox', 'MPC Toolbox', 'Robotics System Toolbox', 'Computer Vision Toolbox', 'RL Toolbox', 'Predictive Maintenance Toolbox'],
    kind: 'software',
    vendorOrOwner: 'MathWorks',
    pillarIds: ['controls', 'ai', 'physical', 'safety'],
    domainIds: ['control-systems', 'kinematics', 'ml', 'reliability'],
    categoryIds: ['cad-cae', 'language'],
    summary:
      'A numerical computing environment and language whose toolboxes cover control design, system identification, robotics, vision and predictive maintenance from one workspace.',
    useCases: [
      'Designing and tuning a controller against an identified plant model',
      'Analysing stability margins and frequency response',
      'Prototyping an algorithm before porting it to C',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: ['src-mathworks'],
    coverageKind: 'ecosystem-reference',
    keywords: ['matlab', 'toolbox', 'control system', 'system identification', 'mathworks', 'numerical'],
  },
  {
    id: 'ent-simulink',
    slug: 'simulink',
    name: 'Simulink',
    aliases: ['Simulink', 'Simscape', 'Simulink Coder', 'Embedded Coder', 'Simulink Real-Time', 'Simscape Electrical', 'Simscape Fluids', 'System Composer', 'MATLAB/Simulink'],
    kind: 'software',
    vendorOrOwner: 'MathWorks',
    pillarIds: ['controls', 'networks', 'safety'],
    domainIds: ['control-systems', 'digital-twin', 'systems-integration'],
    categoryIds: ['cad-cae', 'simulator'],
    summary:
      'Block-diagram modelling and simulation with physical-domain libraries through Simscape and production code generation through Embedded Coder, which is what makes model-based design a delivery route rather than an analysis exercise.',
    useCases: [
      'Model-based design with generated production C for a controller',
      'Plant and controller co-simulation before hardware',
      'Real-time execution on a HIL target',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: ['src-mathworks'],
    coverageKind: 'ecosystem-reference',
    keywords: ['simulink', 'simscape', 'embedded coder', 'model based design', 'code generation', 'hil'],
  },
  {
    id: 'ent-control-design-open',
    slug: 'open-control-design-tools',
    name: 'Open control design and optimisation tools',
    aliases: ['python-control', 'Python Control Library', 'SciPy.signal', 'GNU Octave', 'Scilab', 'Xcos', 'CasADi', 'ACADO', 'do-mpc', 'GEKKO', 'Pyomo', 'FORCES Pro', 'Jupyter'],
    kind: 'library',
    vendorOrOwner: 'Open-source projects and Embotech',
    pillarIds: ['controls'],
    domainIds: ['control-systems'],
    categoryIds: ['framework', 'algorithm'],
    summary:
      'Open and low-cost alternatives for control analysis and model predictive control, including the symbolic and automatic-differentiation frameworks that make nonlinear MPC tractable.',
    useCases: [
      'Formulating a nonlinear MPC problem and generating solver code',
      'Control analysis without a commercial licence',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['casadi', 'acado', 'do-mpc', 'gekko', 'python-control', 'octave', 'mpc', 'optimisation'],
  },
  {
    id: 'ent-labview',
    slug: 'labview',
    name: 'LabVIEW',
    aliases: ['LabVIEW', 'LabVIEW Control Design', 'NI VeriStand', 'NI TestStand'],
    kind: 'software',
    vendorOrOwner: 'NI (Emerson)',
    pillarIds: ['controls', 'electronics'],
    domainIds: ['control-systems', 'instrumentation'],
    categoryIds: ['cad-cae', 'ide-toolchain'],
    summary:
      'A dataflow graphical programming environment for test, measurement and control, closely tied to NI acquisition and real-time hardware.',
    useCases: ['Building an automated test bench with synchronised acquisition', 'Deploying control to a CompactRIO target'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['labview', 'dataflow', 'ni', 'veristand', 'teststand', 'crio', 'test bench'],
  },
  {
    id: 'ent-ros',
    slug: 'ros-2',
    name: 'ROS 2',
    aliases: ['ROS', 'ROS 2', 'ROS2', 'Robot Operating System', 'ros2_control', 'rclcpp', 'rclpy', 'ROS-on-Linux'],
    kind: 'framework',
    vendorOrOwner: 'Open Source Robotics Foundation',
    pillarIds: ['controls'],
    domainIds: ['robotics-middleware', 'navigation', 'vision'],
    categoryIds: ['framework'],
    summary:
      'The dominant robotics middleware: a node graph over a DDS transport, with quality-of-service settings, lifecycle-managed nodes and a very large package ecosystem for perception, planning and control.',
    useCases: [
      'Composing perception, planning and control as separate processes with defined interfaces',
      'Recording and replaying a full sensor session for offline debugging',
      'Reusing maintained navigation and manipulation stacks rather than writing them',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: ['src-ros2-releases', 'src-ros2-lyrical'],
    coverageKind: 'ecosystem-reference',
    models: [
      { name: 'Lyrical Luth', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'Released 22 May 2026, supported to May 2031.' },
      { name: 'Kilted Kaiju', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'Released May 2025. Recommended Gazebo pairing is Ionic.' },
      { name: 'Jazzy Jalisco', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'Long-term support release, May 2024. Recommended Gazebo pairing is Harmonic.' },
      { name: 'Humble Hawksbill', lifecycle: 'maintained', lifecycleAsOf: '2026-07-30', note: 'Long-term support release.' },
      { name: 'Rolling Ridley', lifecycle: 'preview', lifecycleAsOf: '2026-07-30', note: 'The rolling development distribution.' },
      { name: 'Iron Irwini', lifecycle: 'deprecated', lifecycleAsOf: '2026-07-30', note: 'End of life.' },
      { name: 'Galactic Geochelone', lifecycle: 'deprecated', lifecycleAsOf: '2026-07-30', note: 'End of life.' },
      { name: 'ROS 1', lifecycle: 'legacy', lifecycleAsOf: '2026-07-30', note: 'The original ROS. Noetic was the final release; new work targets ROS 2.' },
    ],
    keywords: ['ros', 'ros 2', 'middleware', 'node', 'topic', 'dds', 'qos', 'jazzy', 'humble', 'lyrical'],
  },
  {
    id: 'ent-dds',
    slug: 'dds-and-robotics-transports',
    name: 'DDS and robotics transports',
    aliases: ['DDS', 'Fast DDS', 'Cyclone DDS', 'Eclipse Cyclone DDS', 'RTI Connext', 'Connext', 'Zenoh', 'LCM', 'gRPC'],
    kind: 'protocol',
    vendorOrOwner: 'Object Management Group, eProsima, Eclipse Foundation, RTI',
    pillarIds: ['controls', 'networks'],
    domainIds: ['robotics-middleware', 'fieldbus'],
    categoryIds: ['protocol', 'framework'],
    summary:
      'The publish-subscribe transports beneath robotics middleware, offering discovery and quality-of-service policies, with Zenoh addressing the wide-area and constrained-link cases DDS handles poorly.',
    useCases: [
      'Tuning reliability and durability per topic rather than per system',
      'Bridging a robot fleet to a remote operations centre',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['dds', 'fast dds', 'cyclone', 'connext', 'zenoh', 'pub sub', 'qos', 'discovery'],
  },
  {
    id: 'ent-robotics-frameworks-alt',
    slug: 'alternative-robotics-frameworks',
    name: 'Alternative robotics frameworks',
    aliases: ['Orocos', 'YARP', 'MOOS-IvP', 'OpenRAVE'],
    kind: 'framework',
    vendorOrOwner: 'Open-source projects',
    pillarIds: ['controls'],
    domainIds: ['robotics-middleware'],
    categoryIds: ['framework'],
    summary:
      'Robotics middleware predating or running alongside ROS, with Orocos still used for hard real-time component execution and MOOS-IvP established in marine autonomy.',
    useCases: ['Hard real-time component execution beside a ROS graph', 'Marine and underwater autonomy'],
    lifecycle: 'maintained',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['orocos', 'yarp', 'moos-ivp', 'openrave', 'real-time components'],
  },
  {
    id: 'ent-motion-planning',
    slug: 'motion-planning-and-manipulation',
    name: 'Motion planning and manipulation',
    aliases: ['MoveIt', 'MoveIt 2', 'MoveIt Calibration', 'OMPL', 'SBPL', 'Tesseract', 'Descartes', 'Pilz industrial motion', 'trajopt', 'TrajOpt', 'CHOMP', 'STOMP', 'IKFast', 'TRAC-IK', 'RelaxedIK'],
    kind: 'framework',
    vendorOrOwner: 'PickNik Robotics, Rice University and open-source projects',
    pillarIds: ['controls', 'physical'],
    domainIds: ['robotics-middleware', 'kinematics'],
    categoryIds: ['framework', 'algorithm'],
    summary:
      'Collision-aware planning and inverse kinematics for arms: sampling-based planners through OMPL, optimisation-based planners, and the solvers that turn a Cartesian goal into joint angles.',
    useCases: [
      'Planning a collision-free path through a cluttered cell',
      'Solving redundant-arm IK with a secondary objective',
      'Cartesian process paths for welding or dispensing',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['moveit', 'ompl', 'ik', 'trac-ik', 'chomp', 'stomp', 'planning', 'collision', 'trajectory'],
  },
  {
    id: 'ent-robot-simulators',
    slug: 'robot-simulators',
    name: 'Robot simulators',
    aliases: ['Gazebo', 'Gazebo Classic', 'Ignition', 'Ignition Gazebo', 'Gazebo Harmonic', 'Gazebo Ionic', 'Gazebo Jetty', 'Webots', 'CoppeliaSim', 'V-REP', 'Isaac Sim', 'NVIDIA Isaac Sim', 'Unity', 'Unreal Engine', 'AirSim', 'Isaac Lab', 'Isaac Gym'],
    kind: 'software',
    vendorOrOwner: 'Open Source Robotics Foundation, Cyberbotics, Coppelia Robotics, NVIDIA',
    pillarIds: ['controls', 'ai'],
    domainIds: ['robotics-middleware', 'mlops', 'navigation'],
    categoryIds: ['simulator'],
    summary:
      'Physics and sensor simulation for robots, from the ROS-native Gazebo line through general-purpose simulators to photorealistic environments used for synthetic data and reinforcement learning.',
    useCases: [
      'Developing and regression-testing autonomy without hardware',
      'Generating labelled synthetic training data',
      'Reinforcement learning at many times real time',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: ['src-gazebo', 'src-nvidia-omniverse'],
    coverageKind: 'ecosystem-reference',
    models: [
      { name: 'Gazebo Jetty', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'The release the Gazebo documentation currently presents as latest.' },
      { name: 'Gazebo Ionic', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'Recommended pairing for ROS 2 Kilted.' },
      { name: 'Gazebo Harmonic', lifecycle: 'current', lifecycleAsOf: '2026-07-30', note: 'Recommended pairing for ROS 2 Jazzy.' },
      {
        name: 'Ignition Gazebo',
        aliases: ['Ignition'],
        lifecycle: 'legacy',
        lifecycleAsOf: '2026-07-30',
        note: 'Former name of the modern Gazebo line. Retained as a search alias.',
      },
      {
        name: 'Gazebo Classic',
        lifecycle: 'deprecated',
        lifecycleAsOf: '2026-07-30',
        note: 'The original Gazebo, superseded by the current line and no longer the recommended target.',
      },
      { name: 'NVIDIA Isaac Sim and Isaac Lab', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      { name: 'Webots', lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
      {
        name: 'CoppeliaSim',
        aliases: ['V-REP'],
        lifecycle: 'current',
        lifecycleAsOf: '2026-07-30',
        note: 'V-REP is the former name of CoppeliaSim and is retained as a search alias only.',
      },
      { name: 'Unity and Unreal Engine with ROS bridges', aliases: ['AirSim'], lifecycle: 'current', lifecycleAsOf: '2026-07-30' },
    ],
    keywords: ['gazebo', 'isaac sim', 'webots', 'coppeliasim', 'v-rep', 'simulation', 'sim2real', 'synthetic'],
  },
  {
    id: 'ent-ros-tooling',
    slug: 'ros-tooling-and-formats',
    name: 'ROS tooling and description formats',
    aliases: ['colcon', 'catkin', 'rosdep', 'rviz2', 'RViz', 'Foxglove', 'Foxglove Studio', 'rqt', 'rosbag2', 'MCAP', 'ROS bag', 'URDF', 'SDF', 'xacro', 'robot_state_publisher', 'tf2'],
    kind: 'software',
    vendorOrOwner: 'Open Source Robotics Foundation, Foxglove',
    pillarIds: ['controls'],
    domainIds: ['robotics-middleware'],
    categoryIds: ['ide-toolchain', 'framework'],
    summary:
      'The build, visualisation, recording and description layer around ROS, including the URDF and SDF robot descriptions and the transform tree that keeps every frame related.',
    useCases: [
      'Visualising sensor data and transforms while debugging',
      'Recording a session to MCAP and replaying it against new code',
      'Describing a robot once for simulation, planning and visualisation',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: ['src-ros2-releases'],
    coverageKind: 'ecosystem-reference',
    keywords: ['colcon', 'rviz', 'foxglove', 'rosbag', 'mcap', 'urdf', 'sdf', 'tf2', 'xacro'],
  },
  {
    id: 'ent-opencv',
    slug: 'opencv',
    name: 'OpenCV',
    aliases: ['OpenCV', 'cv2', 'OpenCV stereo', 'ArUco', 'Charuco'],
    kind: 'library',
    vendorOrOwner: 'OpenCV.org',
    pillarIds: ['controls'],
    domainIds: ['vision'],
    categoryIds: ['framework'],
    summary:
      'The standard computer vision library: calibration, feature detection, stereo, tracking and classical image processing, with fiducial marker support widely used for calibration and pose reference.',
    useCases: [
      'Camera calibration and lens distortion correction',
      'Fiducial-based pose estimation for hand-eye calibration',
      'Classical preprocessing ahead of a learned model',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: ['src-opencv'],
    coverageKind: 'ecosystem-reference',
    keywords: ['opencv', 'calibration', 'aruco', 'stereo', 'feature', 'image processing', 'cv2'],
  },
  {
    id: 'ent-pcl-open3d',
    slug: 'point-cloud-libraries',
    name: 'Point cloud and 3D libraries',
    aliases: ['PCL', 'Point Cloud Library', 'Open3D', 'MeshLab', 'CloudCompare', 'COLMAP', 'OpenMVS', 'RealityCapture'],
    kind: 'library',
    vendorOrOwner: 'Open-source projects and Capturing Reality',
    pillarIds: ['controls'],
    domainIds: ['vision'],
    categoryIds: ['framework'],
    summary:
      'Processing and reconstruction for 3D data: filtering, segmentation and registration of point clouds, plus photogrammetric reconstruction from image sets.',
    useCases: ['Registering a scan to a CAD model', 'Segmenting a part from a bin for grasp planning', 'Reconstructing a scene from photographs'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['pcl', 'open3d', 'point cloud', 'registration', 'icp', 'colmap', 'photogrammetry', 'mesh'],
  },
  {
    id: 'ent-machine-vision-software',
    slug: 'industrial-machine-vision-software',
    name: 'Industrial machine vision software',
    aliases: ['Halcon', 'MVTec Halcon', 'Cognex VisionPro', 'VisionPro', 'ViDi', 'Cognex Deep Learning', 'NVIDIA VisionWorks', 'cuImage'],
    kind: 'software',
    vendorOrOwner: 'MVTec, Cognex, NVIDIA',
    pillarIds: ['ot', 'controls'],
    domainIds: ['workcell', 'vision'],
    categoryIds: ['framework', 'vendor-platform'],
    summary:
      'Commercial vision libraries and configurable inspection environments with the deterministic behaviour, tooling and support that production inspection is usually specified around.',
    useCases: ['Configurable inline inspection without bespoke code', 'Deep-learning defect classification within a supported vision platform'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['halcon', 'cognex', 'visionpro', 'vidi', 'inspection', 'defect', 'machine vision'],
  },
  {
    id: 'ent-slam',
    slug: 'slam-and-visual-odometry',
    name: 'SLAM and visual odometry',
    aliases: ['SLAM', 'ORB-SLAM3', 'RTAB-Map', 'LIO-SAM', 'FAST-LIO', 'LOAM', 'LeGO-LOAM', 'VINS-Mono', 'VINS-Fusion', 'Kimera', 'Cartographer', 'SLAMcore', 'g2o', 'GTSAM', 'Ceres Solver', 'Kalibr'],
    kind: 'library',
    vendorOrOwner: 'Research groups and open-source projects',
    pillarIds: ['controls'],
    domainIds: ['vision', 'navigation'],
    categoryIds: ['framework', 'algorithm'],
    summary:
      'Simultaneous localisation and mapping implementations across visual, visual-inertial and LiDAR-inertial sensing, with the graph optimisation back ends and calibration tools they depend on.',
    useCases: [
      'Building a map and localising within it with no external infrastructure',
      'Fusing IMU and LiDAR for odometry that survives feature-poor environments',
      'Calibrating extrinsics between camera and IMU',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['slam', 'orb-slam', 'rtab-map', 'lio-sam', 'fast-lio', 'gtsam', 'ceres', 'loop closure', 'odometry'],
  },
  {
    id: 'ent-sensor-sdks',
    slug: 'perception-sensor-sdks',
    name: 'Perception sensor SDKs',
    aliases: ['RealSense SDK', 'Intel RealSense SDK', 'ZED SDK', 'Stereolabs SDK', 'Orbbec SDK', 'Ouster SDK', 'rs_driver', 'Velodyne driver', 'MiDaS'],
    kind: 'library',
    vendorOrOwner: 'Intel, Stereolabs, Orbbec, Ouster, RoboSense',
    pillarIds: ['controls', 'electronics'],
    domainIds: ['vision', 'optics'],
    categoryIds: ['framework'],
    summary:
      'Vendor drivers and SDKs that expose depth, point cloud and IMU streams with the calibration and synchronisation the hardware provides, usually with ROS wrappers alongside.',
    useCases: ['Getting time-synchronised depth and inertial data into a perception pipeline'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['realsense', 'zed', 'ouster', 'orbbec', 'driver', 'sdk', 'depth', 'point cloud'],
  },
  {
    id: 'ent-navigation-stacks',
    slug: 'navigation-stacks',
    name: 'Navigation stacks',
    aliases: ['Nav2', 'Navigation2', 'costmap', 'TEB', 'TEB local planner', 'DWA', 'dynamic window approach', 'Hybrid A*', 'AMCL', 'Autoware', 'Autoware.Universe', 'Apollo', 'Baidu Apollo'],
    kind: 'framework',
    vendorOrOwner: 'Open Source Robotics Foundation, Autoware Foundation, Baidu',
    pillarIds: ['controls'],
    domainIds: ['navigation'],
    categoryIds: ['framework', 'algorithm'],
    summary:
      'Complete autonomy stacks for ground vehicles: layered costmaps, global and local planners, controllers and recovery behaviours, with Autoware and Apollo covering the road-vehicle case.',
    useCases: [
      'Autonomous point-to-point navigation with dynamic obstacle avoidance',
      'Behaviour trees for recovery when a plan fails',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['nav2', 'costmap', 'teb', 'dwa', 'amcl', 'autoware', 'apollo', 'behaviour tree', 'recovery'],
  },
  {
    id: 'ent-fleet-management',
    slug: 'fleet-management-and-interop',
    name: 'Fleet management and interoperability',
    aliases: ['Open-RMF', 'RMF', 'VDA 5050', 'MassRobotics AMR Interop', 'MiR Fleet', 'fleet manager', 'traffic management'],
    kind: 'framework',
    vendorOrOwner: 'Open Robotics, VDA, MassRobotics',
    pillarIds: ['controls', 'ot'],
    domainIds: ['navigation', 'workcell'],
    categoryIds: ['framework', 'protocol'],
    summary:
      'Coordination above the individual robot: task allocation, traffic and zone management across a shared floor, and the interoperability interfaces that let vehicles from different vendors share one controller.',
    useCases: [
      'Preventing deadlock where several vehicles need the same corridor',
      'Running a mixed-vendor fleet from one control system',
      'Integrating robots with lifts and doors',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: ['src-vda5050'],
    coverageKind: 'ecosystem-reference',
    keywords: ['open-rmf', 'vda 5050', 'fleet', 'traffic', 'task allocation', 'interoperability', 'deadlock'],
  },
  {
    id: 'ent-robot-programming-languages',
    slug: 'robot-vendor-programming-languages',
    name: 'Robot vendor programming languages',
    aliases: ['KRL', 'RAPID', 'KAREL', 'TP', 'AS language', 'VAL3', 'Polyscope', 'teach pendant', 'URScript'],
    kind: 'language',
    vendorOrOwner: 'KUKA, ABB, FANUC, Kawasaki, Stäubli, Universal Robots',
    pillarIds: ['ot'],
    domainIds: ['workcell'],
    categoryIds: ['language'],
    summary:
      'Proprietary languages and pendant environments for industrial arms, each with its own motion primitives, frame handling and I/O model, which is a large part of why arm vendors are not interchangeable.',
    useCases: ['Programming a cell in the vendor language the integrator and customer support'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['krl', 'rapid', 'karel', 'val3', 'polyscope', 'teach pendant', 'vendor language'],
  },
  {
    id: 'ent-robot-offline-programming',
    slug: 'robot-simulation-and-offline-programming',
    name: 'Robot simulation and offline programming',
    aliases: ['RoboDK', 'RobotStudio', 'ABB RobotStudio', 'ROBOGUIDE', 'FANUC ROBOGUIDE', 'KUKA.Sim', 'MotoSim', 'Yaskawa MotoSim', 'Visual Components', 'DELMIA', 'Process Simulate', 'Tecnomatix'],
    kind: 'software',
    vendorOrOwner: 'RoboDK, ABB, FANUC, KUKA, Yaskawa, Dassault Systèmes, Siemens',
    pillarIds: ['ot'],
    domainIds: ['workcell', 'manufacturing'],
    categoryIds: ['simulator'],
    summary:
      'Offline programming and cell simulation that verifies reach, cycle time and collisions before the robot exists, then posts a program in the vendor language.',
    useCases: [
      'Proving reach and cycle time at quotation stage',
      'Programming without occupying production hardware',
      'Validating a layout change before it is built',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['robodk', 'robotstudio', 'roboguide', 'offline programming', 'cycle time', 'reach', 'collision'],
  },
] as const
