import type { EcosystemEntity } from '../types'

/** Test, measurement, laboratory and fabrication equipment. */
export const testEquipmentEntities: readonly EcosystemEntity[] = [
  {
    id: 'ent-oscilloscopes',
    slug: 'oscilloscopes',
    name: 'Oscilloscopes',
    aliases: ['oscilloscope', 'Keysight InfiniiVision', 'Infiniium', 'Tektronix', 'Rigol DS', 'Rigol MSO', 'Rigol DHO', 'Siglent SDS', 'PicoScope', 'LeCroy', 'Teledyne WaveRunner', 'Hantek', 'mixed-signal oscilloscope', 'MSO'],
    kind: 'test-equipment',
    vendorOrOwner: 'Keysight, Tektronix, Rigol, Siglent, Teledyne LeCroy and others',
    pillarIds: ['electronics'],
    domainIds: ['instrumentation', 'microelectronics'],
    categoryIds: ['test-measurement'],
    summary:
      'Time-domain measurement of voltage, from bench models for board bring-up to high-bandwidth instruments for signal integrity, most now mixed-signal with digital channels and protocol decode.',
    useCases: [
      'Board bring-up and power-rail verification',
      'Catching an intermittent glitch with advanced triggering',
      'Measuring switching loss and dead time on a converter',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['oscilloscope', 'mso', 'bandwidth', 'trigger', 'probe', 'signal integrity', 'bring-up'],
  },
  {
    id: 'ent-logic-protocol-analysers',
    slug: 'logic-and-protocol-analysers',
    name: 'Logic and protocol analysers',
    aliases: ['logic analyser', 'logic analyzer', 'Saleae', 'Saleae Logic', 'DSLogic', 'Total Phase', 'Beagle I2C', 'Beagle SPI', 'Beagle USB', 'protocol decoder', 'Wireshark'],
    kind: 'test-equipment',
    vendorOrOwner: 'Saleae, Total Phase, DreamSourceLab and others',
    pillarIds: ['compute', 'electronics'],
    domainIds: ['firmware', 'instrumentation'],
    categoryIds: ['test-measurement'],
    summary:
      'Capture and decode of digital buses, turning edges on SPI, I2C, UART or USB into readable transactions so a firmware fault can be attributed to the bus or to the code.',
    useCases: ['Proving whether a sensor actually answered', 'Measuring bus timing against the datasheet'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['logic analyser', 'saleae', 'spi', 'i2c', 'uart', 'decode', 'protocol'],
  },
  {
    id: 'ent-can-tools',
    slug: 'automotive-and-fieldbus-analysers',
    name: 'Automotive and fieldbus analysers',
    aliases: ['Vector CANoe', 'CANalyzer', 'CANape', 'PEAK', 'PCAN-View', 'PCAN Trace', 'Kvaser', 'Intrepid', 'neoVI', 'Softing', 'TH Link', 'Procentec', 'Anybus Inspector', 'NetScout', 'PROFINET analyser', 'EtherCAT analyser'],
    kind: 'test-equipment',
    vendorOrOwner: 'Vector Informatik, PEAK-System, Kvaser, Softing, Procentec',
    pillarIds: ['networks', 'compute'],
    domainIds: ['fieldbus', 'firmware'],
    categoryIds: ['test-measurement'],
    summary:
      'Bus capture, simulation and diagnosis for CAN and industrial networks, including residual-bus simulation and the physical-layer measurements that find a marginal segment.',
    useCases: [
      'Validating an ECU against a communication matrix',
      'Diagnosing intermittent PROFINET or EtherCAT faults on a running line',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['canoe', 'canalyzer', 'can', 'profinet', 'ethercat', 'residual bus', 'diagnosis'],
  },
  {
    id: 'ent-meters',
    slug: 'multimeters-and-meters',
    name: 'Multimeters, LCR and power meters',
    aliases: ['multimeter', 'DMM', 'Fluke', 'Fluke 87V', 'Fluke 289', 'clamp meter', 'Keysight 34461A', '3458A', 'Brymen', 'Hioki', 'Chauvin Arnoux', 'LCR meter', 'Keysight E4980', 'Hioki IM3536', 'DER EE', 'power analyser', 'Yokogawa WT', 'Hioki PW', 'Zimmer LMG', 'impedance meter'],
    kind: 'test-equipment',
    vendorOrOwner: 'Fluke, Keysight, Hioki, Yokogawa and others',
    pillarIds: ['electronics'],
    domainIds: ['instrumentation', 'power-electronics'],
    categoryIds: ['test-measurement'],
    summary:
      'Scalar measurement instruments: handheld and bench multimeters, clamp meters for non-contact current, LCR bridges for component characterisation, and power analysers for efficiency work.',
    useCases: ['Commissioning checks and fault finding', 'Measuring converter efficiency across load', 'Characterising magnetics'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['multimeter', 'fluke', 'lcr', 'clamp meter', 'power analyser', 'efficiency', 'calibration'],
  },
  {
    id: 'ent-sources-loads',
    slug: 'power-supplies-loads-and-generators',
    name: 'Power supplies, electronic loads and generators',
    aliases: ['bench power supply', 'Rigol DP832', 'Siglent SPD3303X', 'Keysight E36311A', 'TDK-Lambda Genesys', 'electronic load', 'Chroma 62000', 'Chroma 63000', 'BK Precision', 'ITECH', 'Maynuo', 'function generator', 'AWG', 'Keysight 33500', '33600', 'Rigol DG', 'Siglent SDG', 'Tektronix AFG'],
    kind: 'test-equipment',
    vendorOrOwner: 'Rigol, Siglent, Keysight, Chroma, TDK-Lambda and others',
    pillarIds: ['electronics'],
    domainIds: ['instrumentation', 'power-electronics'],
    categoryIds: ['test-measurement'],
    summary:
      'Programmable sources and sinks: bench supplies, electronic loads that emulate a real load profile, and function and arbitrary waveform generators for stimulus.',
    useCases: [
      'Characterising a converter across line and load',
      'Injecting a defined stimulus to measure a system response',
      'Battery discharge profiling',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['power supply', 'electronic load', 'awg', 'function generator', 'stimulus', 'characterisation'],
  },
  {
    id: 'ent-rf-instruments',
    slug: 'spectrum-and-network-analysers',
    name: 'Spectrum, network and VNA instruments',
    aliases: ['spectrum analyser', 'network analyser', 'VNA', 'NanoVNA', 'miniVNA', 'Rohde & Schwarz', 'Siglent SSA', 'EMC pre-compliance'],
    kind: 'test-equipment',
    vendorOrOwner: 'Keysight, Rohde & Schwarz, Siglent and others',
    pillarIds: ['electronics'],
    domainIds: ['instrumentation', 'microelectronics'],
    categoryIds: ['test-measurement'],
    summary:
      'Frequency-domain instruments for emissions, antenna and impedance work, including the low-cost VNAs that made pre-compliance measurement practical outside a test house.',
    useCases: ['EMC pre-compliance scanning before a formal test', 'Antenna matching and return-loss measurement'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['spectrum analyser', 'vna', 'emc', 'emissions', 'antenna', 'return loss', 'pre-compliance'],
  },
  {
    id: 'ent-debug-probes',
    slug: 'debug-and-trace-probes',
    name: 'Debug and trace probes',
    aliases: ['J-Link', 'Segger J-Link', 'J-Trace', 'ST-Link', 'ST-Link V3', 'DAPLink', 'CMSIS-DAP', 'Lauterbach', 'TRACE32', 'PEmicro', 'XDS110', 'XDS200', 'ULINKpro', 'Black Magic Probe', 'JTAG', 'SWD', 'ETM', 'ITM', 'serial wire viewer', 'Arm DS-5'],
    kind: 'test-equipment',
    vendorOrOwner: 'Segger, STMicroelectronics, Lauterbach, Arm and others',
    pillarIds: ['compute'],
    domainIds: ['firmware', 'realtime'],
    categoryIds: ['test-measurement', 'ide-toolchain'],
    summary:
      'Hardware debuggers over JTAG and SWD, and the trace units that reconstruct instruction flow without stopping the target, which is often the only way to see a real-time fault.',
    useCases: [
      'Stepping firmware on the target rather than in a simulator',
      'Non-intrusive instruction trace on a timing-sensitive fault',
      'Production flashing',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['jtag', 'swd', 'j-link', 'st-link', 'trace32', 'etm', 'debug', 'flash'],
  },
  {
    id: 'ent-current-thermal-probes',
    slug: 'current-and-thermal-instruments',
    name: 'Current probes and thermal instruments',
    aliases: ['current probe', 'Tektronix TCP', 'Keysight N2893A', 'Pearson', 'LEM probe', 'thermal camera', 'FLIR', 'lux meter', 'laser power meter', 'optical spectrum analyser', 'thermal imaging'],
    kind: 'test-equipment',
    vendorOrOwner: 'Tektronix, Keysight, Teledyne FLIR and others',
    pillarIds: ['electronics', 'safety'],
    domainIds: ['instrumentation', 'optics', 'reliability'],
    categoryIds: ['test-measurement'],
    summary:
      'Non-contact current measurement and thermal or optical imaging, used both during design for loss and hotspot analysis and in service for predictive maintenance.',
    useCases: ['Measuring switching current without breaking the circuit', 'Finding a hot joint or failing bearing before it fails'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['current probe', 'thermal camera', 'flir', 'hotspot', 'predictive maintenance', 'rogowski'],
  },
  {
    id: 'ent-metrology',
    slug: 'mechanical-metrology',
    name: 'Mechanical metrology',
    aliases: ['caliper', 'micrometer', 'dial indicator', 'height gauge', 'torque wrench', 'torque analyser', 'force gauge', 'Mark-10', 'Imada', 'laser tracker', 'Faro', 'Leica', 'Hexagon', 'API', 'CMM', '3D scanner', 'Artec', 'Creality', 'Revopoint', 'surface roughness tester', 'hardness tester', 'strain-gauge DAQ', 'HBM', 'Vishay'],
    kind: 'test-equipment',
    vendorOrOwner: 'Faro, Hexagon, Mitutoyo, HBM and others',
    pillarIds: ['physical', 'ot'],
    domainIds: ['materials', 'manufacturing', 'kinematics'],
    categoryIds: ['test-measurement'],
    summary:
      'Dimensional and mechanical measurement from hand tools through coordinate measuring machines to laser trackers, which is how a robot cell or a machined part is proved against its drawing.',
    useCases: [
      'First-article inspection against GD&T',
      'Registering a robot cell to a real coordinate frame',
      'Reverse engineering an existing part by scan',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['cmm', 'laser tracker', 'caliper', 'gd&t', '3d scanner', 'inspection', 'calibration'],
  },
  {
    id: 'ent-environmental-test',
    slug: 'environmental-and-reliability-test',
    name: 'Environmental and reliability test equipment',
    aliases: ['thermal chamber', 'climatic chamber', 'Thermotron', 'ESPEC', 'Weiss', 'HALT', 'HASS', 'vibration shaker', 'shaker table', 'LDS', 'Data Physics', 'Sentek', 'salt spray', 'IP test rig', 'ingress test', 'drop tester', 'burn-in'],
    kind: 'test-equipment',
    vendorOrOwner: 'Thermotron, ESPEC, Data Physics and others',
    pillarIds: ['safety', 'physical'],
    domainIds: ['reliability', 'materials'],
    categoryIds: ['test-measurement', 'fabrication'],
    summary:
      'Chambers and shakers that apply thermal, humidity, vibration, ingress and shock stress, used both to qualify against a standard and to precipitate latent defects early.',
    useCases: [
      'Qualifying an enclosure to an IP rating',
      'Accelerated life testing to find the weak component before the field does',
      'Thermal cycling to expose solder joint fatigue',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['halt', 'hass', 'thermal cycling', 'vibration', 'ingress', 'ip rating', 'accelerated life'],
  },
  {
    id: 'ent-failure-analysis-equipment',
    slug: 'failure-analysis-equipment',
    name: 'Failure analysis equipment',
    aliases: ['X-ray inspection', 'CSAM', 'scanning acoustic microscopy', 'SEM', 'EDS', 'cross-section', 'decapsulation'],
    kind: 'test-equipment',
    pillarIds: ['safety', 'electronics'],
    domainIds: ['reliability', 'microelectronics'],
    categoryIds: ['test-measurement'],
    summary:
      'Instruments that establish why a part failed rather than that it failed: X-ray and acoustic imaging for internal defects, and electron microscopy with elemental analysis for material and interface faults.',
    useCases: ['Identifying voiding or cracking inside a BGA joint', 'Establishing the root cause of a field return'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['x-ray', 'sem', 'eds', 'csam', 'root cause', 'failure analysis', 'bga'],
  },
  {
    id: 'ent-pcb-assembly',
    slug: 'pcb-assembly-and-rework',
    name: 'PCB assembly and rework equipment',
    aliases: ['soldering station', 'Hakko', 'Weller', 'Metcal', 'JBC', 'hot air rework', 'BGA rework', 'reflow oven', 'stencil printer', 'pick and place', 'CHMT', 'Neoden', 'AOI', 'flying probe', 'bed of nails', 'ICT', 'conformal coating', 'THT', 'SMD'],
    kind: 'test-equipment',
    vendorOrOwner: 'Hakko, Weller, JBC, Neoden and others',
    pillarIds: ['electronics'],
    domainIds: ['microelectronics'],
    categoryIds: ['fabrication', 'test-measurement'],
    summary:
      'Equipment for building and reworking boards, from hand soldering through desktop placement and reflow to automated optical inspection and in-circuit test.',
    useCases: ['Assembling prototype boards in-house', 'Reworking a fine-pitch or BGA part', 'Screening a production batch by AOI'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['soldering', 'reflow', 'pick and place', 'aoi', 'ict', 'rework', 'bga', 'stencil'],
  },
  {
    id: 'ent-daq',
    slug: 'data-acquisition',
    name: 'Data acquisition systems',
    aliases: ['DAQ', 'NI PXI', 'cDAQ', 'cRIO', 'MCC', 'HBM QuantumX', 'Dewesoft', 'imc', 'Beckhoff measurement terminals', 'USB DAQ'],
    kind: 'test-equipment',
    vendorOrOwner: 'National Instruments, HBM, Dewesoft and others',
    pillarIds: ['electronics', 'controls'],
    domainIds: ['instrumentation', 'control-systems'],
    categoryIds: ['test-measurement'],
    summary:
      'Multi-channel synchronised measurement systems for test benches and field trials, where consistent timing across channels matters as much as the accuracy of any one of them.',
    useCases: ['Instrumenting a vehicle or machine for a test campaign', 'Synchronised strain, temperature and vibration capture'],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['daq', 'pxi', 'crio', 'quantumx', 'synchronised', 'test bench', 'acquisition'],
  },
  {
    id: 'ent-fabrication',
    slug: 'fabrication-equipment',
    name: 'Fabrication equipment',
    aliases: ['3D printer', 'FDM', 'SLA', 'SLS', 'CNC mill', 'CNC', 'laser cutter', 'waterjet', 'composite layup', 'vacuum bagging', 'universal testing machine', 'hardness tester', 'silicone casting'],
    kind: 'test-equipment',
    pillarIds: ['physical', 'ot'],
    domainIds: ['materials', 'manufacturing'],
    categoryIds: ['fabrication'],
    summary:
      'Workshop and laboratory means of making parts: additive processes across FDM, SLA and SLS, subtractive machining and cutting, composite layup, and the mechanical testing that validates the result.',
    useCases: [
      'Producing a functional prototype in days rather than weeks',
      'Machining a fixture or bracket to tolerance',
      'Casting soft actuators in silicone',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['3d printing', 'fdm', 'sla', 'sls', 'cnc', 'laser cutter', 'waterjet', 'composite', 'prototype'],
  },
  {
    id: 'ent-hil-rigs',
    slug: 'hil-and-real-time-test-systems',
    name: 'HIL and real-time test systems',
    aliases: ['dSPACE', 'MicroLabBox', 'SCALEXIO', 'ControlDesk', 'Speedgoat', 'NI VeriStand', 'OPAL-RT', 'Typhoon HIL', 'Concurrent Real-Time', 'hardware-in-the-loop', 'HIL', 'SIL', 'PIL', 'NI TestStand', 'ECU-TEST'],
    kind: 'test-equipment',
    vendorOrOwner: 'dSPACE, Speedgoat, OPAL-RT, National Instruments, Typhoon HIL',
    pillarIds: ['networks', 'controls', 'compute'],
    domainIds: ['digital-twin', 'control-systems', 'realtime'],
    categoryIds: ['test-measurement', 'simulator'],
    summary:
      'Real-time platforms that run a plant model fast enough to fool a real controller, so control software can be tested against faults and edge cases that would be dangerous or impossible on real hardware.',
    useCases: [
      'Testing an ECU or PLC against simulated sensor faults',
      'Closed-loop validation before hardware exists',
      'Automated regression of control software across an operating envelope',
    ],
    lifecycle: 'current',
    lifecycleAsOf: '2026-07-30',
    officialSourceIds: [],
    coverageKind: 'ecosystem-reference',
    keywords: ['hil', 'sil', 'pil', 'dspace', 'speedgoat', 'opal-rt', 'real-time', 'virtual commissioning'],
  },
] as const
